### ISSUE TITLE
Sprint Goal Q2-1 (31 Mar - 13 Apr)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1003]
## Q2 Initiatives

Key: 🚀public launch  🪴internal/partner  🔎exploratory/R&D

### Landing 🚀
- [x] rfcx/biodiversity-analytics#986
- [x] rfcx/biodiversity-analytics#990
- [x] rfcx/biodiversity-analytics#991
- [x] rfcx/biodiversity-analytics#999

### Project publish workflow 🚀
- [ ] Gather additional requirements/expectations for publish workflow
- [x] rfcx/biodiversity-analytics#1002

### Insight dashboard and map 🚀
- [ ] Propose navigation (sidebar/topbar) to bridge guest and project member use cases

### Internal CNNs 🪴
- [x] https://github.com/rfcx/biodiversity-analytics/issues/998

### Auto-validate detections 🪴
_Not in this sprint_

### Clustering usability 🚀
_Not in this sprint_

## Other goals
- [x] rfcx/engineering-support#325
- [ ] rfcx/arbimon#1202 ___ON PAUSE___
- [x] rfcx/arbimon#1205 
- [ ] Make the PR project usable for the science team
  - [x] rfcx/arbimon#1203
  - [x] rfcx/arbimon#1204
- [ ] Migrating recordings to Core
  - [ ] Complete another 100 projects
- [ ] Download buttons
  - [x] rfcx/arbimon#1206
  - [ ] rfcx/arbimon#1207
- [ ] Arbimon branding (requested by Bourhan, may need to assign some to Tree/Frongs)
  - [x] rfcx/arbimon-uploader#187
  - [x] rfcx/companion-android#682
  - [x] rfcx/rfcx-org#109

## User support
- [ ] Arbimon
  - [x] rfcx/arbimon#1197 ___IN PROGRESS___
  - [x] rfcx/arbimon#1198 ___IN PROGRESS___
- [ ] Uploader
  - [x] rfcx/arbimon-uploader#186
  - [ ] (optional) rfcx/arbimon-uploader#188
- [ ] Insights
  - [x] rfcx/biodiversity-analytics#1006
