### ISSUE TITLE
Sprint Goal Q2-2 (14 Apr - 27 Apr)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1013]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Landing 🎈
- [ ] Finalise design/content of 1 featured work page

### Project publish workflow 🎈
- [ ] Gather additional requirements/expectations for publish workflow
- [x] rfcx/biodiversity-analytics#1002

### Insight dashboard and map 🎈
- [x] Propose navigation (sidebar/topbar) to bridge guest and project member use cases

### Internal CNNs 🪧
- [x] https://github.com/rfcx/biodiversity-analytics/issues/998

### Auto-validate detections 🪧
_Not in this sprint_

### Clustering usability 🎈
- [x] rfcx/arbimon#1222

## Other goals
- [x] Make the PR project usable for the science team
  - [x] rfcx/arbimon#1203
- [ ] Migrating recordings to Core
  - [ ] Complete another **69/100** projects
- [ ] Download buttons
  - [x] rfcx/arbimon#1206
  - [ ] rfcx/arbimon#1207 __ON PROGRESS__
- [ ] Arbimon branding (requested by Bourhan, may need to assign some to Tree/Frongs)
  - [x] rfcx/arbimon-uploader#187
  - [x] rfcx/companion-android#682
  - [x] rfcx/rfcx-org#109
  - [x] #1020
  
- [ ] Other (optional)
  - [x] rfcx/arbimon#1217 __ON STAGING__
  - [x] rfcx/arbimon#1218
  - [x] rfcx/arbimon#1219

## User support
Uploader
- [x] rfcx/arbimon-uploader#188 

Arbimon
- [x] rfcx/arbimon#1197 
- [x] rfcx/arbimon#1213 
- [x] rfcx/arbimon#1214 __ON STAGING__
- [x] rfcx/arbimon#1215
- [x] rfcx/arbimon#1208 

Insights
- [x] rfcx/biodiversity-analytics#1017 __ON PROGRESS__
