### ISSUE TITLE
Sprint Goal Q2-3 (28 Apr - 11 May)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1014]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Landing 🎈
- [x] rfcx/biodiversity-analytics#1015
- [x] rfcx/biodiversity-analytics#986
- [x] rfcx/biodiversity-analytics#990
- [x] rfcx/biodiversity-analytics#999

### Project publish workflow 🎈
- [x] rfcx/biodiversity-analytics#982

### Insight dashboard and map 🎈
- [x] rfcx/biodiversity-analytics#1024
- [x] rfcx/biodiversity-analytics#1017 

### Internal CNNs 🪧
- [x] rfcx/rfcx-sdk-python#24
- [x] rfcx/rfcx-sdk-python#23
- [x] rfcx/prediction-service#97

### Auto-validate detections 🪧
_Not in this sprint_

### Clustering usability 🎈
-  [x] rfcx/arbimon#1231

### Global Summary Report
- [x] rfcx/biodiversity-analytics#1022

## Other goals
Quality
- [x] rfcx/arbimon#1219
- [x] rfcx/arbimon#1218

## User support
Arbimon
- [x] rfcx/arbimon#1214
- [x] rfcx/arbimon#1220

Insights
- [x] rfcx/biodiversity-analytics#1021
