### ISSUE TITLE
Sprint Goal Q2-4 (12 May - 25 May)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1028]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Clustering usability 🎈
-  [x] rfcx/arbimon#1231
- [x] https://github.com/rfcx/arbimon/issues/1220

### Internal CNNs 🪧
- [x] Sci team can validate squirrel detections in Arbimon
- [x] rfcx/rfcx-api#456
- [x] Test out review functionality on Core staging

### Project publish workflow 🎈
- [x] rfcx/biodiversity-analytics#982
- [x] rfcx/biodiversity-analytics#1036

### Insight dashboard and map 🎈
- [x] rfcx/biodiversity-analytics#1024
- [x] rfcx/biodiversity-analytics#1017 
- [x] rfcx/biodiversity-analytics#1031

### Landing 🎈
- [x] rfcx/biodiversity-analytics#1015

### Auto-validate detections 🪧
_Not in this sprint_

### Global Summary Report
- [x] rfcx/biodiversity-analytics#1030

## Other goals
Quality
- [ ] Migrating recordings to Core __IN PROGRESS__ **(25 out of 100)**
- [x] rfcx/arbimon#1219
- [x] rfcx/arbimon#1218
- [x] Improve email text/graphics in emails
- [x] Send all emails from no-reply@arbimon.org 
- [x] https://github.com/rfcx/arbimon/issues/1239
- [x] https://github.com/rfcx/arbimon/issues/1145 

Other
- [x] rfcx/biodiversity-analytics#1029
- [x] Finalise scope and initiate the Hitachi project
- [ ] Upload files from 3 SD cards (Tembé Reserve, Brazil (Guardians))

## User support
Arbimon
- [x] rfcx/arbimon#1240 __WAITING USER FEEDBACK__
- [x] rfcx/arbimon#1233
- [x] rfcx/arbimon#1236
- [x] rfcx/arbimon#1242
- [x] rfcx/arbimon-uploader#190
- [x] rfcx/arbimon#1244

Insights
- [x] rfcx/biodiversity-analytics#1019
