### ISSUE TITLE
Sprint Goal Q2-6 (16 - 22 Jun)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1054]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Landing 🎈
- [x] rfcx/biodiversity-analytics#1037
- [ ] rfcx/biodiversity-analytics#1038
- [x] rfcx/biodiversity-analytics#1046
- [x] rfcx/biodiversity-analytics#1047

### Insight dashboard and map 🎈
- [x] rfcx/biodiversity-analytics#1044
- [x] rfcx/biodiversity-analytics#1043
- [ ] rfcx/biodiversity-analytics#1042

### Project publish workflow 🎈
- [ ] rfcx/biodiversity-analytics#1045

### Auto-validate detections 🪧
_Not in this sprint_

### Internal CNNs -> Species Validation (Q3)
- [x] rfcx/biodiversity-analytics#1040 
- [x] rfcx/biodiversity-analytics#1041 
- [ ] rfcx/biodiversity-analytics#1048
- [x] rfcx/biodiversity-analytics#998

## Other goals
Quality
- [x] rfcx/arbimon#1247
- [x] rfcx/arbimon#1271

## User support
Arbimon
- [x] rfcx/arbimon#1253
- [x] rfcx/arbimon#1260
- [x] rfcx/arbimon#1269
- [x] rfcx/engineering-support#336
