### ISSUE TITLE
Sprint Goal Q3-1 (7 - 20 July 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1062]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Landing 🎈
 rfcx/biodiversity-analytics#1063
 rfcx/biodiversity-analytics#1066
 rfcx/biodiversity-analytics#1070
 rfcx/biodiversity-analytics#1037
 rfcx/biodiversity-analytics#1038

### Insight dashboard and map 🎈
- [x] rfcx/biodiversity-analytics#1043
- [ ] rfcx/biodiversity-analytics#1042

### Project publish workflow 🎈
- [ ] rfcx/biodiversity-analytics#1045

### Auto-validate detections 🪧
_Not in this sprint_
- [x] rfcx/biodiversity-analytics#1063
- [x] rfcx/biodiversity-analytics#1066
- [x] rfcx/biodiversity-analytics#1070
- [x] rfcx/biodiversity-analytics#1080
- [x] rfcx/biodiversity-analytics#1037
### Internal CNNs -> Species Validation (Q3)
- [x] rfcx/biodiversity-analytics#1041 
- [ ] rfcx/biodiversity-analytics#1048
- [x] rfcx/biodiversity-analytics#998
- [x] rfcx/biodiversity-analytics#1065

## Other goals
Quality

Elephant projects
- [x] Get the elephant model uploaded to Core
- [x] Run the elephant model batch job
- [x] Copy detections to PM results for review

## User support
Arbimon
- [x] rfcx/arbimon#1253
- [x] rfcx/arbimon#1260
