### ISSUE TITLE
Sprint Goal Q3-2 (21 Jul - 3 Aug)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1074]
## Q2 Initiatives

Key: 🎈public launch  🪧internal/partner  🔎exploratory/R&D

### Landing 🎈
~~- [ ] rfcx/biodiversity-analytics#1038~~
- [x] rfcx/biodiversity-analytics#1077
- [x] rfcx/biodiversity-analytics#1078
- [x] #1080 
- [x] #1084 
- [x] #1086

### Insight dashboard and map 🎈
- [x] rfcx/biodiversity-analytics#1043
- [ ] rfcx/biodiversity-analytics#1042

### Project publish workflow 🎈
- [ ] rfcx/biodiversity-analytics#1045

### Auto-validate detections 🪧
_Not in this sprint_

### Internal CNNs -> Species Validation (Q3)
- [ ] rfcx/biodiversity-analytics#1048
- [x] rfcx/biodiversity-analytics#998
- [x] rfcx/biodiversity-analytics#1065

## Other goals
Quality
- [x] rfcx/engineering-support#340

## User support
Arbimon
- [x] rfcx/arbimon#1293
- [x] rfcx/arbimon#1294
- [x] rfcx/engineering-support#377
- [x] rfcx/engineering-support#379
- [x] rfcx/arbimon#1295
