### ISSUE TITLE
Sprint Goal Q3-3 (4 Aug - 17 Aug)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1091]
# Overview

Landing progress and roadmap from v1 to v1.1 [Figma](https://www.figma.com/file/bOdjGktR4D6luJZLPM1q4n/Landing-page---implementation-plan?type=whiteboard&node-id=34%3A252&t=GMod30cXjSmWQ7wW-1)

# Sprint Goal

### Arbimon Legacy
- [x] rfcx/arbimon#1301
- [x] When user clicks on Arbimon logo it should link back to the new landing page

### Insights
- [ ] #1111

### Home
- [x] Globe section - new design with species only (no countries or projects)
- [ ] rfcx/biodiversity-analytics#1092

### Publications page - @grindarius 
- [x] V1 UI: rfcx/biodiversity-analytics#1085
- [x] #1110
- [ ] V1.1 API: rfcx/biodiversity-analytics#1037

### FAQ
- [x] rfcx/biodiversity-analytics#1087 

### Team - @naluinui 
- [x] rfcx/biodiversity-analytics#1089 

### Contact 
- [x] rfcx/biodiversity-analytics#1086 
- [ ] Update Salesforce with new "where did you hear"/"referred_from" field

### Deployment and Launch
- [ ] Domain setup: Move arbimon.rfcx.org to arbimon.org and bio.rfcx.org to insights.arbimon.org
- [ ] Setup auth to work with arbimon.org
- [ ] Create landing as separate application and setup ingress for specific page OR Build new landing pages to replace existing landing

### Adjustments from marketing feedback
See this [🔗 Doc](https://docs.google.com/document/d/1C9WCzIFhxrXLbmoRu-Rgs9Yn6fD0ZbXyW0VTP13f0DY/edit) for more detail

Fixing priority should be: bugs, copy, graphics, spacing/layout

Bugs:
- [x] https://github.com/rfcx/biodiversity-analytics/issues/1109
- [x] rfcx/biodiversity-analytics#1096
- [x] rfcx/biodiversity-analytics#1097

Content (copy & graphics):
- [x] rfcx/biodiversity-analytics#1095
- [x] #1108
- [x] rfcx/biodiversity-analytics#1101
- [x] rfcx/biodiversity-analytics#1093

Layout
- [x] #1107
- [x] #1106
- [x] rfcx/biodiversity-analytics#1098
- [x] rfcx/biodiversity-analytics#1094
- [x] rfcx/biodiversity-analytics#1099
- [x] rfcx/biodiversity-analytics#1100
- [x] rfcx/biodiversity-analytics#1103
- [x] rfcx/biodiversity-analytics#1104
- [x] rfcx/biodiversity-analytics#1102

# Stretch Goal

### Login / Registration
- [ ] New design for login/registration

### v1.1
...any of the tasks from the Figma

### CNN
- [ ] Classification summary working
