### ISSUE TITLE
Sprint Goal Q3-4 (18 - 31 Aug)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1115]
# Overview

Landing progress and roadmap from v1 to v1.1 [Figma](https://www.figma.com/file/bOdjGktR4D6luJZLPM1q4n/Landing-page---implementation-plan?type=whiteboard&node-id=34%3A252&t=GMod30cXjSmWQ7wW-1)

Arbimon landing [adjustments doc](https://docs.google.com/document/d/1C9WCzIFhxrXLbmoRu-Rgs9Yn6fD0ZbXyW0VTP13f0DY/edit) by Marketing.

# Sprint Goal

### Landing @naluinui 
- [x] rfcx/biodiversity-analytics#1094
- [x] #1126
- [ ] Merge completed landing into develop (without navigation changes)
- [ ] Launch on 25 Aug

### Login / Registration
- [ ] rfcx/biodiversity-analytics#1117

### v1.1 @grindarius 
- [ ] Publications API: rfcx/biodiversity-analytics#1037

HOLD:
- [ ] #1122
- [ ] #1123
- [ ] #1124
- [ ] #1125
- [ ] Get 4-5 new featured cases from Marketing
- [ ] Mixpanel analytics

### Science team automation
- [ ] Automate the creation of large soundscape jobs
  - [ ] Create GitHub actions workflow with inputs matching soundscape parameters
  - [ ] Python script for sending slack notification
  - [ ] Wrapper to create soundscape playlist and job (in ready state)
  - [ ] Call existing playlist2soundscape python script
- [x] rfcx/arbimon#1316

### CNN
- [ ] Classification summary working

### RFCx website
- [ ] Setup "Contentful" for Marketing team to try

# User supports
### Partner supports
  - [x] rfcx/arbimon#1300
  - [x] rfcx/engineering-support#396
  - [x] rfcx/engineering-support#404
  - [x] rfcx/arbimon#1311
  - [x] rfcx/engineering-support#407
  - [x] rfcx/engineering-support#409
  - [ ] Run scripts on active project 2nd round - need more disscusion
### Other supports
  - [x] rfcx/biodiversity-analytics#1114
  - [x] rfcx/arbimon#1305
  - [x] rfcx/arbimon#1309
  - [x] rfcx/arbimon#1307
