### ISSUE TITLE
Sprint Goal Q3-5 (1 - 14 Sep)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1127]
### Arbimon automations (for Science)
- [ ] PM
  - [x] rfcx/arbimon#1317
- [ ] Ecological analysis
  - [x] rfcx/arbimon#1318
  - [x] rfcx/arbimon#1330
  - [ ] rfcx/arbimon-automations#2 <- stretch
- [ ] Automate the creation of large *soundscape* jobs
  - [x] rfcx/arbimon-soundscapes#8
  - [x] rfcx/arbimon-soundscapes#9
  - [x] rfcx/arbimon-soundscapes#10
  - [ ] Python script for sending slack notification

### Partner support
  - [x] rfcx/engineering-support#396
  - [x] rfcx/arbimon#1311

### User support
- [x] rfcx/biodiversity-analytics#1120
- [x] rfcx/arbimon#1319

### Corruption
- [x] rfcx/dev-tools#5

### Dashboard v1
- [x] rfcx/biodiversity-analytics#1137
- [x] #1144
- [x] #1145
- [x] rfcx/biodiversity-analytics#1140
- [x] rfcx/biodiversity-analytics#1135
- [x] rfcx/biodiversity-analytics#1136

### Login / Registration
- [ ] rfcx/biodiversity-analytics#1117
- [x] User is signed up to mailing list in mailchimp

### CNN
- [x] rfcx/biodiversity-analytics#1139 
- [x] Fix CNN job list missing fields
- [x] rfcx/biodiversity-analytics#1138
- [ ] rfcx/biodiversity-analytics#1048
- [ ] List species in CNN on create job page
- [ ] Filter for best X detections per site per day
