### ISSUE TITLE
[Insight overview] User can see the project metric overview

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1135]
<img width="687" alt="Screen Shot 2566-09-14 at 14 25 27" src="https://github.com/rfcx/biodiversity-analytics/assets/9149523/944af77f-1938-4500-814b-867ddd71fa8a">

### Project metric overview
👇 Use these as metrics instead of ones in screenshots above
Deployment sites = Number of sites with recorders deployed
Threatened over all species detected = Number of Near Threatened, Vulnerable, Endangered, & Critically Endangered species over total species found. /* to be confirmed */
Total detections = Total number of species calls detected
Recordings (hours) = Total hours of recordings captured

## Tasks
- [x] UI: to show the metrics
- [x] UI: Loading state when calling data from API
- [x] UI: Error handling
- [x] API: that returns 4 metric information
