### ISSUE TITLE
Sprint Goal Q3-6 (15 - 28 Sep) 

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1146]
## Partner & user support
@koonchaya 
- [x] rfcx/arbimon#1338
- [x] rfcx/arbimon#1335
- [x] rfcx/biodiversity-analytics#1143
- [x] rfcx/arbimon#1332
- [x] rfcx/biodiversity-analytics#1158

## Dashboard V1
@grindarius @rassokhina-e 

Figma: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=2245-8165&mode=dev

### Outcome 
A new Arbimon dashboard page to show the overview of the projects and quick actions to the main features

- [x] rfcx/biodiversity-analytics#1145
- [x] https://github.com/rfcx/arbimon/issues/1337
- [x] rfcx/biodiversity-analytics#1144 
- [x] rfcx/biodiversity-analytics#1163
- [ ] Use the reusable component for metrics (same as the one in Insight page)

## Insights
@naluinui @grindarius

Figma: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=2245-8165&mode=dev
🎥 from UX: https://drive.google.com/file/d/1HgWXpkvM50zO3rRdcRWde_zzizE2HcsS/view?usp=drive_link

### Outcome
A new Arbimon Insights page that enables the user to see the Insights report of the project 

#### Main  @rassokhina-e 
- [x] rfcx/biodiversity-analytics#1147
- [x] rfcx/biodiversity-analytics#1167
- [x] rfcx/biodiversity-analytics#1154
- [x] rfcx/biodiversity-analytics#1159
- [x] rfcx/biodiversity-analytics#1160

#### Overview @grindarius
- [x] rfcx/biodiversity-analytics#1135
- [x] rfcx/biodiversity-analytics#1148

#### Threatened species @naluinui 
- [x] rfcx/biodiversity-analytics#1136 
- [x] rfcx/biodiversity-analytics#1151
- [x] rfcx/biodiversity-analytics#1150
- [x] rfcx/biodiversity-analytics#1152

#### Summary (stretch goal)  @grindarius
- [x] rfcx/biodiversity-analytics#1153

## Arbimon automations (for Science)
@antonyharfield 

### Outcome
Science team can run batch soundscapes themselves
- [x] rfcx/arbimon-soundscapes#11
- [ ] rfcx/arbimon-soundscapes#12
- [ ] rfcx/biodiversity-analytics#1157

## Landing v1.1
@grindarius 

- [x] rfcx/biodiversity-analytics#1037
