### ISSUE TITLE
User can filter overview page with start & end date

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1161]
![Screenshot 2023-09-18 at 4 22 30 PM](https://github.com/rfcx/biodiversity-analytics/assets/9149523/b98ef665-0b18-4906-965a-b447a60ebcec)
![Screenshot 2023-09-18 at 4 27 42 PM](https://github.com/rfcx/biodiversity-analytics/assets/9149523/1f62227f-498e-46e3-98b3-8d822f0a8a77)

### Tasks
- [ ] When the user click on date, show date picker for the user to pick the start & end date for the report

### Other related tasks
Also, the report data should be reflected by the start & end date
- [ ] Overview - metrics should be filtered by start & end date
- [ ] Threatened species - species detected should be filtered by start & end date
- [ ] Map - species richness & detection should be filtered by start & end date
