### ISSUE TITLE
Sprint Goal Q3-7 (29 Sep - 12 Oct)

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1169]
## Partner & user support
- [x] rfcx/arbimon#1333
- [x] rfcx/biodiversity-analytics#1165
- [x] rfcx/arbimon#1340
- [x] rfcx/engineering-support#429
- [x] rfcx/engineering-support#432

## Insights

Figma: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=2245-8165&mode=dev
🎥 from UX: https://drive.google.com/file/d/1HgWXpkvM50zO3rRdcRWde_zzizE2HcsS/view?usp=drive_link

### Outcome
A new Arbimon Insights page that enables the user to see the Insights report of the project 

#### Main @rassokhina-e 
- [x] #1147
- [x] #1159
- [x] #1160

#### Map & graph visualization @naluinui 
- [x] #1178
- [x] #1179
- [x] #1180
- [x] #1181 
- [x] #1182
- [x] #1183
- [x] #1190

#### Threatened species @naluinui 
- [x] #1176
- [x] #1177

#### Summary @grindarius 
- [x] #1153
- [x] #1171
- [x] #1172
- [x] #1173
- [x] #1174
- [ ] API - #1168 

#### Test
- [x] #1184
- [ ] Post signup add to mailchimp

## Miscellaneous
- [x] #1170
