### ISSUE TITLE
Sprint Goal Q4-2 (26 Oct - 8 Nov)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1191]
## Partner & User support
- [x] rfcx/arbimon-legacy#1349
- [x] rfcx/arbimon-legacy#1358
- [x] rfcx/biodiversity-analytics#1220
- [x] rfcx/biodiversity-analytics#1223
- [x] rfcx/biodiversity-analytics#1222
- [x] rfcx/biodiversity-analytics#1242
- [x] rfcx/arbimon-legacy#1363

Optional
- [x] rfcx/engineering-support#437

## Create & Edit a project @naluinui 
- [x] #1224
- [x] #1229

## Country
- [x] Sync site country from Core to Arbimon
- [x] #1260
- [x] #1261

## Syncing
- [ ] #1240
- [x] #1239

## Publishing Insights

- [x] #1241
- [x] #1265

#### Main
- [x] #1225
- [x] #1227

#### Summary @grindarius 
- [x] #1230
- [x] #1232
- [x] #1234
- [x] #1231
- [x] #1233
- [x] #1243

#### Test
- [ ] Post signup add to mailchimp
- [x] Create a new project workflow to make sure it is correct

## Other quality

Landing
- [x] #1211
- [x] #1212
- [x] #1213
- [x] #1214
- [x] #1215
- [x] #1218
- [x] #1245
- [x] #1246
- [x] #1247
- [x] #1248
- [x] #1249
- [x] #1250
- [x] #1251
- [x] #1262

My project @rassokhina-e 
- [x] #1219

Dashboard @rassokhina-e 
- [x] #1210 
- [x] #1216
- [x] #1217
- [x] #1197

## Miscellaneous
- [x] #1170 

## Recorder app
Android
- [x] rfcx/arbimon-recorder-android#29
- [x] rfcx/arbimon-recorder-android#28
- [x] rfcx/arbimon-recorder-android#30
- [x] rfcx/arbimon-recorder-android#31
- [ ] rfcx/arbimon-recorder-android#32
- [ ] rfcx/arbimon-recorder-android#35
- [ ] rfcx/arbimon-recorder-android#23
