### ISSUE TITLE
Sprint Goal Q4-1 (11-24 Oct)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1201]
## Partner & user support
- [x] rfcx/arbimon#1355
- [x] rfcx/arbimon#1356
- [ ] rfcx/arbimon#1349
- [x] rfcx/engineering-support#442 
- [x] rfcx/biodiversity-analytics#1187 @rassokhina-e
- [x] rfcx/arbimon#1351
- [x] rfcx/biodiversity-analytics#1189
- [x] rfcx/engineering-support#436

**Optional**
- [ ] rfcx/engineering-support#421
- [x] rfcx/biodiversity-analytics#1175
- [x] rfcx/engineering-support#437 

## Quality
- [x] #1192
- [ ] #1195
- [x] #1194 @rassokhina-e
- [x] #1196 @rassokhina-e
- [x] #1198 @rassokhina-e
- [ ] #1199
- [x] #1200 @rassokhina-e
- [x] #1205
- [x] #1207 @rassokhina-e
- [ ] Fix authentication problem between Insigths and Arbimon @rassokhina-e _In Progress_
- [x] Create new columns country and country_code into the Arbimon DB, get this data + the timezone from the core side @rassokhina-e _In Progress_

## Insights
Figma: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=2245-8165&mode=dev
🎥 from UX: https://drive.google.com/file/d/1HgWXpkvM50zO3rRdcRWde_zzizE2HcsS/view?usp=drive_link

### Outcome
A new Arbimon Insights page that enables the user to see the Insights report of the project 

#### Main @rassokhina-e 
- [x] #1160
- [x] #1208
- [x] #1209

#### Map & graph visualization @naluinui 
- [x] #1183
- [x] #1202
- [x] #1203
- [x] #1204

#### Summary @grindarius 
- [x] #1153
- [x] #1171
- [x] #1172
- [x] #1173
- [x] #1174
- [ ] API - #1168 

#### Test
- [ ] Post signup add to mailchimp

## Miscellaneous
- [x] #1170 
---
## My projects
- [x] #1193
## Dashboard
**Analyses**
- [x] #1197
