### ISSUE TITLE
Sprint Goal Q4-3 (9-22 Nov 2023)

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1237]
## Publishing - Insights
Objective: User can add extra information and publish the insight report to the world

#### Highlighted species 
- [x] rfcx/arbimon#1185
- [x] rfcx/arbimon#1235 @rassokhina-e 
- [x] rfcx/arbimon#1256 @rassokhina-e 
- [x] rfcx/arbimon#1258 @rassokhina-e 
- [x] rfcx/arbimon#1257 @rassokhina-e 
- [x] rfcx/arbimon#1253 @naluinui 

#### Stakeholders
- [x] rfcx/arbimon#1269 @naluinui 
- [x] rfcx/arbimon#1270 @grindarius 
- [x] rfcx/arbimon#1275 @grindarius 
- [x] rfcx/arbimon#1233 @grindarius 
- [x] rfcx/arbimon#1290 @grindarius 

#### Publishing
- [x] rfcx/arbimon#1225 @grindarius 
- [x] rfcx/arbimon#1227  @grindarius 
- [x] rfcx/arbimon#1282 @naluinui 
- [x] rfcx/arbimon#1226 @naluinui 
- [x] rfcx/arbimon#1228 @naluinui 
- [x] rfcx/arbimon#1252 @koonchaya  
- [x] rfcx/arbimon#1283 @RatreeOchn 
- [x] Change edit button to Edit project settings

#### Navigation

- [x] rfcx/arbimon#1254 @naluinui 
- [x] rfcx/arbimon#1255 @naluinui 
- [x] rfcx/arbimon#1276 @rassokhina-e 
- [x] My projects link is not working -- it should link to `/my-projects` @naluinui 
- [x] rfcx/arbimon#1287 @naluinui 
- [x] rfcx/arbimon#1289 @rassokhina-e 
- [x] rfcx/arbimon-legacy#1382
- [x] #1313

## Create project
Objective: User can input start-end date (of funding period) to the project

- [x] rfcx/arbimon#1271 @RatreeOchn @naluinui 
- [x] rfcx/arbimon#1272 @RatreeOchn 
- [x] rfcx/arbimon#1273 @RatreeOchn 
- [x] rfcx/arbimon#1274 @naluinui  
- [x] rfcx/arbimon#1284 @RatreeOchn 
- [x] Change text in Project objectives "Create" to "Establish" (first objective)

#### Overview
- [x] rfcx/arbimon#1259 @rassokhina-e 
- [x] rfcx/arbimon#1268 @rassokhina-e 
- [x] rfcx/arbimon#1279 @rassokhina-e 
- [x] rfcx/arbimon#1216 @rassokhina-e 

#### Legacy
- [ ] rfcx/arbimon-legacy#1370 @rassokhina-e 
- [ ] rfcx/arbimon-legacy#1368 @rassokhina-e 
- [x] Move detection to another project if the user moves site

#### Others
- [x] rfcx/arbimon#1266 @RatreeOchn 
- [ ] rfcx/arbimon#1280 @RatreeOchn 
- [ ] rfcx/arbimon#1281 @grindarius 
- [ ] rfcx/arbimon#1291 @koonchaya 
- [x] rfcx/arbimon#1285 @RatreeOchn 
- [ ] rfcx/arbimon#1286 @antonyharfield 
- [ ] rfcx/arbimon#1240 @koonchaya 

#### User supoort
- [x] rfcx/engineering-support#453 @grindarius 
- [x] rfcx/arbimon-legacy#1366  @rassokhina-e 
- [x] rfcx/arbimon-legacy#1365 @RatreeOchn 
- [x] rfcx/engineering-support#437
