### ISSUE TITLE
Sprint Goal Q4-4 (23 Nov - 6 Dec 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1299]
## Projects (directory)
🎯 Objectives: User can browse through all the published projects in one place
📸 Design: https://www.figma.com/file/vgrNAtCXbe5rPinIW44JgN/%E2%9A%99%EF%B8%8F-Arbimon-Landing-Page?type=design&node-id=4400-15465&mode=dev

### Front-end
- [ ] #1309 @naluinui 
- [ ] #1304 @naluinui 
- [ ] #1305 @naluinui 

### Back-end
- [ ] #1333 @grindarius 

### Back-end
- [ ] #1328 @antonyharfield 
- [ ] #1327 @antonyharfield 
- [ ] #1335 @grindarius 
- [ ] #1336 @grindarius 

### Account settings
🎯 Objectives: User can edit their info & add their organization

![Screen Shot 2566-11-20 at 19 48 32](https://github.com/rfcx/arbimon/assets/9149523/d5dc993b-854e-4d77-a0f5-85235b740294)

- [ ] #1310 @RatreeOchn 
- [ ] #1311 @RatreeOchn 
- [ ] #1312 @rassokhina-e 
### Roles
🎯 Objectives: Insights has user information to show specific data to specific users
 
- [ ] https://github.com/rfcx/arbimon/issues/1306 @grindarius 
- [x] #1307 @grindarius 

## My projects
🎯 Objectives: User can create new projects and see all the projects

- [x] #1317 @RatreeOchn 
- [x] #1318 @RatreeOchn 
- [x] #1292 @RatreeOchn 
- [ ] #1334 @RatreeOchn 
- [x] #1319 @naluinui 
- [x] #1320 @naluinui 
## Quality
- [ ] #1281 @grindarius 
- [ ] #1288
- [x] #1300
- [x] #1301 @RatreeOchn 
- [ ] https://github.com/rfcx/arbimon/issues/1295 @naluinui 
- [x] #1314 @rassokhina-e 
- [ ] #1315 @RatreeOchn 
- [ ] #1323 @naluinui 
- [x] #1325 @grindarius 
- [ ] #1332 @grindarius 

#### Legacy
- [ ] rfcx/arbimon-legacy#1368 @rassokhina-e 
- [ ] #1297 @rassokhina-e 
- [ ] Move export RFM job, so it doesn't slow down Arbimon @rassokhina-e 

## 🧹 Dev housekeeping

- [ ] https://github.com/rfcx/arbimon/issues/1294
- [x] #1338
- [x] #1298 

## User supports
- [x] rfcx/engineering-support#478
- [x] #1331 
- [x] rfcx/arbimon-legacy#1377
- [x] rfcx/arbimon-legacy#1380
- [x] rfcx/engineering-support#474
- [x] rfcx/arbimon-legacy#1381
- [x] rfcx/engineering-support#475
- [x] rfcx/engineering-support#476
- [x] rfcx/engineering-support#479

## Testing
🎯 Objectives: have test cases in place for all the new flow of Arbimon
Dashboard: https://rfcx.testpad.com/project/14/folder/f9/report/?auth=500771e4dff6b1c0596597def6467197
Insight: https://rfcx.testpad.com/project/14/folder/f10/report/?auth=df7e011626427d789a9c94d4a1505ecf
My projects: https://rfcx.testpad.com/project/14/folder/f7/report/?auth=408142c3628fe253c489af294c269d8
Account settings: https://rfcx.testpad.com/project/14/folder/f11/report/?auth=6a02d44338e57aa3364bef5b0898abee

### From previous sprints
- [x] Test cases: overview page (dashboard)
  - stat in each section
- [x] Test cases: Insight - overview page
  - project summary
  - highlighted species 
  - insight hero (country, date, objective)
  - other statistic
- [x] Test cases: Insight - publishing flow
  - different states for different user roles (login / not login), data types (data, no data)
  - view as guest
  - hide, show (publish, unpublish)
- [x] Test cases:  Insight - other stat pages (richness, activity, spotlight)

### This sprint
- [ ] Test cases: project directory
- [x] Test cases: my projects
- [x] #1348
