### ISSUE TITLE
Project directory - create JSON raw data and types

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1309]
![Screen Shot 2566-11-20 at 19 32 21](https://github.com/rfcx/arbimon/assets/9149523/d62f05fe-b344-491d-9bef-af4d370f119a)

![Screen Shot 2566-11-27 at 08 47 07](https://github.com/rfcx/arbimon/assets/9149523/16bdb8e9-29dc-4374-af00-6baa6d9a1f58)

# Task
- [x] Design the data structure you need for this UI
- [x] Create raw data in typescript object format (similar to files in this folder https://github.com/rfcx/arbimon/tree/develop/apps/cli/src/db/seeders/_data) 
- [ ] Create related types 

This data will be used as a mock data for  #1304 and #1305
