### ISSUE TITLE
Show list of projects

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1318]
# Tasks

- [x] List of project cards that each of them includes: 
- default image by objective
- project name
- country
- objectives: use shorten objectives
- project blurb
- project status (Live/Hidden)
- [x] Shorten objectives with ... (as shown in screenshot below) if it's too long & show a tooltip with all objectives when the user hovers over it
- [x] Lazy loading: show 20 to start with & scroll down to load more
<img width="331" alt="Screen Shot 2566-11-21 at 14 00 49" src="https://github.com/rfcx/arbimon/assets/87486094/99f6e073-9fdd-47d0-8d06-914b5a887cad">

https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=6263-72358&mode=design&t=EdxeKbDIu5BlFi9n-4
