### ISSUE TITLE
Add default project image

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1319]
Add project image by objective (if there is more than 1 objective, random the image). Use these 6 images to begin with
https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=6609-72386&mode=dev

//TODO: @koonchaya to get final default images

### Tasks
- [ ] Host default images from S3 from #1327 
- [x] Add field `image` to `location_project_profile` table
- [x] When the user creates a project, randomly add the image url to `location_project_profile` by the objectives
