### ISSUE TITLE
API: Support project details in the list

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1320]
### Tasks
- [ ] DB: Create view to form this data in the database?
- [x] API: Implement the following API
- [x] API: receive `limit` and `offset` as query (so user can get it as pagination if needed)

Endpoint
``` http
GET: /projects?offset=0&limit=20
Content-Type: application/json
Authorization: Bearer [token]
```

Response
An array of projects with the following information

``` typescript
"data": [{ 
  name: string // project.name
  isMyProject: boolean // check if mine
  // from location_project_profile table
  countries: string // 1 country | "Multiple countries"
  objectives: string[]
  summary: string
  image: sting
  // from project_version table
  isPublished: boolean // published status 
}],
"offset": 0,
"limit": 20,
"total": 1

```
