### ISSUE TITLE
Sprint Goal Q4-5 (7-20 Dec 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1340]
## Projects (directory)
🎯 Objectives: User can browse through all the published projects in one place
📸 Design: https://www.figma.com/file/vgrNAtCXbe5rPinIW44JgN/%E2%9A%99%EF%B8%8F-Arbimon-Landing-Page?type=design&node-id=4400-15465&mode=dev
@naluinui @RatreeOchn @grindarius 
- [x] #1345 
- [x] #1346 
- [x] #1360
- [x] https://github.com/rfcx/arbimon/issues/1316
- [x] #1364

### Back end
- [x] #1361
- [x] #1378
- [ ] #1333 @grindarius 

## Account settings
🎯 Objectives: User can edit their info & add their organization

### Back-end
- [ ] #1327 @antonyharfield 
- [ ] #1335 @grindarius 
- [ ] #1336 @grindarius 

### Front-end
- [x] #1311 @rassokhina-e 

### Roles
🎯 Objectives: Insights has user information to show specific data to specific users
 
- [x] https://github.com/rfcx/arbimon/issues/1306 @grindarius 
- [x] #1363
- [x] #1395

## Summary (Stakeholders)
🎯 Objectives: User can add primary contact and show project member
📸 Design: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=5240-51288&mode=design&t=qwXHz6MTxLit861h-4
@rassokhina-e @RatreeOchn 
- [x] Default primary contact with project owner and email
- [x] #1370
- [x] #1371
- [x] #1372
- [x] #1373
- [x] #1374
- [ ] Selected project members and primary contact show on summary(Insights) and project information (Project (directory))
- [x] #1379
- [x] #1382

## Quality
🎯 Objectives: Improvements and adjustments of overall dev.arbimon.org

- [ ] https://github.com/rfcx/arbimon/issues/1286 @antonyharfield
- [x] #1343 @rassokhina-e 
- [x] Add view less under conservation status if there are more than... species @naluinui 
- [x] #1351 @RatreeOchn 
- [x] #1357 @naluinui 
- [x] #1315
- [x] #1323 
- [x] #1332 @grindarius 
- [ ] #1334 (removed)
- [x] #1365 @RatreeOchn 
- [x] #1381
- [ ] #1384 @RatreeOchn 
- [ ] #1385 @RatreeOchn 
- [x] https://github.com/rfcx/arbimon/issues/1295

#### Legacy
- [ ] https://github.com/rfcx/arbimon-legacy/issues/1390
- [x] #1349
- [ ] rfcx/arbimon-legacy#1368 @rassokhina-e 
- [ ] #1297 @rassokhina-e 

## 🧹 Dev housekeeping

- [ ] https://github.com/rfcx/arbimon/issues/1294
- [x] #1338 @rassokhina-e 

## User support
- [x] #1362
- [x] rfcx/arbimon-legacy#1392
- [x]  rfcx/arbimon-legacy#1387
- [x] #1339 
- [x] rfcx/engineering-support#484
- [x] rfcx/engineering-support#486
- [ ]  rfcx/arbimon-legacy#1398

## Testing
🎯 Objectives: have test cases in place for all the new flow of Arbimon
Dashboard: https://rfcx.testpad.com/project/14/folder/f9/report/?auth=500771e4dff6b1c0596597def6467197
Insight: https://rfcx.testpad.com/project/14/folder/f10/report/?auth=df7e011626427d789a9c94d4a1505ecf
My projects: https://rfcx.testpad.com/project/14/folder/f7/report/?auth=408142c3628fe253c489af294c269d8
Account settings: https://rfcx.testpad.com/project/14/folder/f11/report/?auth=6a02d44338e57aa3364bef5b0898abee

- [ ] Test cases: project directory
- [ ] Test cases: summary - stakeholder: primary contact, project members
- [ ] Test 
  - [x] Create project
  - [x] My Projects
  - [x] Overview 
  - [x] Insights
  - [x] Project settings
  - [x] Account settings
  - [x] Links inside New Arbimon should redirect to correct page
  - [x] Sync cases: Overview, Insights 

#### Login flow
- [x] #1355
- [x] #1356

#### Legacy
- [ ] Update the style to match with the new Arbimon (next sprint)
- [ ] Move export RFM job, so it doesn't slow down Arbimon @rassokhina-e 
- [x] #1375

#### Adjustments
- [x] #1366
- [x] #1367
