### ISSUE TITLE
Project information - user can see brief summary of the project

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1360]
![Screen Shot 2566-12-07 at 09 29 38](https://github.com/rfcx/arbimon/assets/9149523/1d726d08-3739-4330-8c55-74bb75a7b203)
รูปประกอบ อาจมีการเปลี่ยนแปลง ดู design ล่าสุดใน [Figma](https://www.figma.com/file/vgrNAtCXbe5rPinIW44JgN/%E2%9A%99%EF%B8%8F-Arbimon-Landing-Page?type=design&node-id=4554-15625&mode=dev)

### Tasks

- [x] Implement the header of this UI (in the orange frame) to show 
  - country & flag
  - image
  - name
  - start end date
  - number of sites (project sites)
  - number of species
  - total detection
  - total recording

- [x] button to View project Insights
- [x] button to close the popup
- [x] info icon to learn more about metrics (project sites, species, ...)
- [x] This UI can be scrollable
