### ISSUE TITLE
My project adjustments

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1367]
Design: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=7318-30883&mode=design&t=E9eQcwxzuqmxdkwA-4

<img width="717" alt="Screen Shot 2566-12-08 at 10 42 26" src="https://github.com/rfcx/arbimon/assets/87486094/f822c342-3e9e-470c-9775-02ad666a8a06">

### Tasks
- [x] Add link to support page (where that green link will be)
- [x] Update loading state (change the word Loading... to better animation - skeleton / spin)
- [ ] Update the error state - use a hyperlink for try again instead of a button (same style of tutorial video link)
