### ISSUE TITLE
Sprint Goal Q4-6 (21 Dec - 10 Jan 2024) 

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1386]
## Legacy
- [x] rfcx/arbimon-legacy#1403
- [ ] rfcx/arbimon-legacy#1390
- [ ] rfcx/arbimon-legacy#1368 @rassokhina-e 
- [x] rfcx/arbimon#1297 @rassokhina-e 
- [x] rfcx/arbimon-legacy#1409
- [ ] Move export RFM job, so it doesn't slow down Arbimon @rassokhina-e 
- [x] Change link of Projecs to redirect to My projects
- [x] #1414
- [ ] use arbimon, arbimon-staging, and arbimon-development buckets for all arbimon related data
- [ ] add manage recordings to the user permissions

## Projects (directory)
🎯 Objectives: User can browse through all the published projects in one place
📸 Design: https://www.figma.com/file/vgrNAtCXbe5rPinIW44JgN/%E2%9A%99%EF%B8%8F-Arbimon-Landing-Page?type=design&node-id=4554-15624&mode=design&t=syn4nJaLXbXUHKnU-4
- [x] rfcx/arbimon#1387
- [x] rfcx/arbimon#1399
- [x] rfcx/arbimon#1405
- [x] rfcx/arbimon#1406
- [ ] rfcx/arbimon#1333 @grindarius 
- [x] rfcx/arbimon#1316 

## On boarding
🎯 Objectives: User can create a new project and choose not to list the project on Arbimon
📸 Design: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=4724-133507&mode=dev
- [x] rfcx/arbimon#1355
- [x] rfcx/arbimon#1389

## Project settings
🎯 Objectives: User can upload project image and choose not to list the unpublished project on Arbimon
📸 Design: https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=5131-176382&mode=dev
- [x] rfcx/arbimon#1390
- [x] rfcx/arbimon#1391
- [x] Add dropdown on side bar: Details and Members
- [x] rfcx/arbimon#1404
- [x] #1410
- [x] #1411
- [x] #1412
- [x] #1413

## Stakeholders
- [x] rfcx/arbimon#1398
- [x] rfcx/arbimon#1403

## Quality
- [x] https://github.com/rfcx/arbimon/issues/1306 
- [x] rfcx/arbimon#1367
- [x] rfcx/arbimon#1392
- [x] rfcx/arbimon#1311 
- [x] rfcx/arbimon#1384 
- [x] rfcx/arbimon#1295 
- [x] rfcx/arbimon#1397
- [x] rfcx/arbimon#1402
- [x] Remove Site under Import from the side bar
- [x] https://github.com/rfcx/arbimon/issues/1401
- [x] #1416

## Testing
🎯 Objectives: have test cases in place for all the new flow of Arbimon
- [ ] Test cases: project directory
- [ ] Test cases: summary - stakeholder: primary contact, project members

## User support
- [x] rfcx/arbimon-legacy#1401
- [x] rfcx/engineering-support#492
- [x] rfcx/arbimon-legacy#1402
- [x] rfcx/arbimon-legacy#1393
- [x] rfcx/engineering-support#493
