### ISSUE TITLE
🗂️ Epic - Add hide site feature to exclude sites from Insights

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1394]
Original request is from sci-team. They want to be able to exclude the sites (eg. test, templates) of the report. 
Additional details:

![Image](https://github.com/rfcx/arbimon/assets/87486094/e0741f09-bee0-4ee0-a798-6e412cf58627)

![Image](https://github.com/rfcx/arbimon/assets/87486094/2eb629b8-37d5-45c4-8379-ce22dc0773c1)

## Plans to work towards

Legacy
- [x] rfcx/arbimon#1767
- [x] rfcx/arbimon#1766
- [x] rfcx/arbimon-legacy#1490

API
- [x] Core API - when update location to 0,0 country should be updated to null

Sync
- [x] Sync - exclude recording & detection number from virtual sites #1595 

Report
- [x] exclude 0,0 or virtual sites from map (overview, insights, project directory)
- [x] prevent user from publishing project insights on a project that only has test (virtual) sites
- [x] update number of sites info description for both overview & insight page to reflect this change
