### ISSUE TITLE
Sprint Goal Q1-1 (11 - 24 Jan 2024) 

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1420]
## Login @rassokhina-e 
- [x] release new login page https://github.com/rfcx/auth0/pull/2
- [x] https://github.com/rfcx/arbimon/issues/1463

## Legacy @rassokhina-e 
- [x] #1477
- [x] rfcx/arbimon-legacy#1418
- [x] rfcx/arbimon-legacy#1421
- [ ] #1474

## Project (directory) @grindarius @naluinui 
🎯 Objectives: User can search for projects and see projects
- [x] rfcx/arbimon#1333
- [x] rfcx/arbimon#1316 
- [x] rfcx/arbimon#1437
- [x] rfcx/arbimon#1424
- [x] rfcx/arbimon#1429
- [x] The numbers of project informations are still empty
- [ ] Figure out updating project metrics problem, the numbers of species/sites/detections are still previous after the incremental sync

#### Project information 
🎯 Objectives: User can edit project url slug
- [x] rfcx/arbimon#1425
- [x] rfcx/arbimon#1413
- [x] rfcx/arbimon#1435 @rassokhina-e 
- [x] rfcx/arbimon#1436

#### Members
🎯 Objectives: User can manage members of the project
- [x] rfcx/arbimon#1411
- [x] rfcx/arbimon#1459
- [x] rfcx/arbimon#1461
- [x] rfcx/arbimon#1467
- [x] rfcx/arbimon-legacy#1420
- [ ] rfcx/arbimon#1470
- [ ] #1473

## Permission/Role @koonchaya
- [x] rfcx/arbimon#1444
- [x] rfcx/arbimon#1426
- [x] rfcx/arbimon#1445
- [x] rfcx/arbimon#1466
- [x] rfcx/arbimon#1468
- [x] #1472

## UI review @RatreeOchn 
- [x] rfcx/arbimon#1423
- [x] rfcx/arbimon#1430
- [x] rfcx/arbimon#1431 @rassokhina-e 
- [x] rfcx/arbimon-legacy#1415 @rassokhina-e 
- [x] rfcx/arbimon#1433 @rassokhina-e 
- [x] rfcx/arbimon#1434
- [x] rfcx/arbimon#1438
- [x] rfcx/arbimon#1439
- [x] rfcx/arbimon#1440
- [x] rfcx/arbimon#1450
- [x] rfcx/arbimon#1455

## Improvements @RatreeOchn 
- [x] rfcx/arbimon-legacy#1403
- [x] rfcx/arbimon#1392
- [x] rfcx/arbimon#1397
- [x] rfcx/arbimon#1402
- [x] rfcx/arbimon#1416
- [x] rfcx/arbimon-legacy#1414 @rassokhina-e 
- [x] rfcx/arbimon#1421 

## API refactor @antonyharfield @grindarius 
- [x] rfcx/arbimon#1447
- [ ] rfcx/arbimon#1448
- [ ] rfcx/arbimon#1449

## Others
- [ ] rfcx/arbimon#1451
- [ ] rfcx/arbimon#1457
