### ISSUE TITLE
Sprint Goal Q1-2 (25 Jan - 7 Feb)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1479]
## Legacy
- [x] rfcx/arbimon#1477
- [x] rfcx/arbimon-legacy#1420
- [x] rfcx/arbimon#1482
- [x] rfcx/arbimon#1483
- [x] rfcx/arbimon-legacy#1440
- [x] rfcx/arbimon-legacy#1429
- [x] rfcx/arbimon-legacy#1441

## Login
- [x] rfcx/arbimon#1463 

## Project (directory)
- [x] rfcx/arbimon#1437
- [x] rfcx/arbimon#1316
- [x] rfcx/arbimon#1476
- [x] rfcx/arbimon#1498

#### Project information
- [x] rfcx/arbimon#1425
- [ ] If the user updates new Arbimon settings we have to update project name, slug on the legacy Arbimon

#### Members
- [ ] rfcx/arbimon#1470 
- [x] rfcx/arbimon#1473
- [x] rfcx/arbimon#1481

## Permissions
- [ ] rfcx/arbimon#1426 - need to check if its still an issue

## Quality
- [x] rfcx/arbimon#1397
- [x] rfcx/arbimon#1478
- [x] rfcx/arbimon#1480

## UI reviews
- [x] rfcx/arbimon#1439
- [x] rfcx/arbimon#1487
- [x] rfcx/arbimon#1488
- [x] rfcx/arbimon#1489
- [x] rfcx/arbimon#1491
- [x] rfcx/auth0#6
- [x] rfcx/arbimon#1494

## API refactor
- [ ] rfcx/arbimon#1448
- [ ] rfcx/arbimon#1449
- [ ] rfcx/arbimon#1451

## Deployment
- [ ] Incremental sync + migration
- [ ] Open search
- [ ] Fill user table
- [ ] Deploy staging on Feb 5
  - [ ] Update kubernetes env for CLI/API
  - [ ] Update kubernetes env for LEGACY
  - [ ] Update auth0 callback/logout/web origin paths for the Bio + Arbimon
  - [ ] Build arbimon + legacy staging
  - [ ] Test websites
- [ ] rfcx/arbimon#1490
- [x] Login between dev and legacy
- [ ] Second banner on Biodiversity
- [x] Update metric numbers on homepage

## User supports
- [x] rfcx/engineering-support#506
- [x] rfcx/engineering-support#507
- [x] rfcx/arbimon-legacy#1425
- [x] rfcx/arbimon-legacy#1426
- [x] rfcx/engineering-support#501
- [x] rfcx/engineering-support#500
- [x] rfcx/engineering-support#492
