### ISSUE TITLE
Sprint Goal Q1-3 (8-21 Feb)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1500]
## New Arbimon

- [x] rfcx/arbimon#1539

#### Before launch
- [x] rfcx/arbimon-legacy#1440
- [x] rfcx/arbimon#1517
- [x] Project information rfcx/arbimon#1425
- [x] Members rfcx/arbimon-legacy#1420
- [x] Members rfcx/arbimon#1481 
- [x] rfcx/arbimon-legacy#1418
- [x] Legacy sidebar
- [x] rfcx/arbimon#1534

#### After launch
- [x] rfcx/arbimon#1544
- [x] rfcx/arbimon#1518
- [ ] Members rfcx/arbimon#1470
- [x] rfcx/arbimon#1524

#### After launch
- [x] rfcx/arbimon#1513

#### Before launch
- [x] rfcx/arbimon#1501
- [x] rfcx/arbimon#1426 
- [x] rfcx/arbimon#1522

#### Before launch
- [x] rfcx/arbimon#1514
- [x] rfcx/arbimon-legacy#1443
  - [x] rfcx/arbimon#1521
  - [x] rfcx/arbimon#1523
  - [x] rfcx/arbimon#1527
  - [x] rfcx/arbimon#1528
  - [x] rfcx/arbimon#1529
  - [x] rfcx/arbimon#1535
  - [x] rfcx/arbimon#1536
  - [x] rfcx/arbimon#1542
  - [ ] rfcx/arbimon#1543
- [x] rfcx/arbimon-legacy#1441
- [x] rfcx/arbimon#1530
- [x] rfcx/arbimon#1533
- [ ] rfcx/arbimon#1538

#### After launch
- [ ] rfcx/arbimon#1497 

#### Before launch
- [x] rfcx/arbimon#1480 
- [x] rfcx/arbimon#1503
- [x] rfcx/arbimon#1502
- [x] rfcx/arbimon#1510
- [x] rfcx/arbimon#1511 
- [x] rfcx/arbimon#1493 
- [x] rfcx/arbimon#1520

#### After launch
- [x] rfcx/arbimon#1549 
- [x] rfcx/arbimon-legacy#1444
- [x] rfcx/arbimon-legacy#1451

#### Optional
- [x] rfcx/arbimon#1519
- [ ] rfcx/arbimon#1507

## Uploader

- [x] rfcx/arbimon-uploader#202
- [x] rfcx/arbimon-uploader#203
- [x] rfcx/arbimon-uploader#204
- [ ] Search for project
- [x] rfcx/arbimon#1540

## User supports
- [x] rfcx/engineering-support#513
- [x] rfcx/engineering-support#500
- [x] rfcx/arbimon-legacy#1430
- [x] rfcx/arbimon-legacy#1406

--- 
_👇 still waiting for final design (so won't be ready until the second week of sprint)_
## Run CNN jobs
VDO https://drive.google.com/file/d/196uLXs9onVu9NmLfSA0hNFrQkRpXAUCM/view?usp=sharing
📸 Design: https://www.figma.com/file/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?type=design&node-id=24-157&mode=design&t=Aey8rwj2jlsPMZ5s-4
🎯 Objectives: User can create CNN jobs
- [x] rfcx/arbimon#1504
- [ ] User can create job
   - [ ] Choose model displays in alphabetical order
   - [ ] Start and end date should be default by the project start-end date
- [ ] Implement date picker/calendar

## Species validations
📸 Design: https://www.figma.com/file/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?type=design&node-id=167-2328&mode=design&t=Aey8rwj2jlsPMZ5s-4
🎯 Objectives: User can use filters (top x per site per day, top x per site, minimum confidence)
- [x] rfcx/arbimon#1506
- [ ] Filters backend
