### ISSUE TITLE
Arbimon Launch 17 Feb Checklist

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#1539]
_All times in GMT/UTC._

## Thursday

- [x] Setup AWS OpenSearch for production @antonyharfield 
- [x] Check secrets are up-to-date @antonyharfield 
- [x] Prepare a maintenance mode page for arbimon.rfcx.org @naluinui 
- [x] Update auth0 callback urls @rassokhina-e 
- [x] Take a backup of any tables we will make manual changes to @antonyharfield 
- [x] Run script to sync core production country code on the site to legacy @rassokhina-e 

## Friday

05:45
- [x] Put Arbimon into maintenance mode (enable page) @antonyharfield 
- [x] Remove old arbimon ingress rules from kubernetes @antonyharfield 

06:00
- [x] Push arbimon `staging` to `master` @grindarius 
- [x] Push arbimon-legacy `staging` to `master` (master will be a new branch, rename the old one first) @rassokhina-e 
- [x] Run arbimon-legacy migrations (sites table updates) @rassokhina-e 

06:15
- [x] Check arbimon.rfcx.org is still pointing to maintenance mode @antonyharfield 
- [x] Check arbimon.org is accessible to us for testing @antonyharfield 
- [x] Check arbimon migrations (insights db) run successfully, make manual changes or rerun if needed (e.g. to delete views) @grindarius 
- [x] Check Auth0 login and logouts (from arbimon and legacy) are working @rassokhina-e 
- [x] Check for missing config/secrets @grindarius , for legacy @rassokhina-e on the kubernetes side

06:30
- [x] Run the user list sync script on the production by doing it against legacy arbimon production (to set location_project_user_role and users table). @grindarius 
- [x] Set the project status to published for any projects marked as public in legacy @antonyharfield
- [x] Sync legacy project's description to arbimon's readme field @antonyharfield

08:00
- [ ] Test @koonchaya 
- [ ] Test @naluinui 
- [ ] Test @RatreeOchn 
- [ ] Make and launch what's new banner @RatreeOchn 

10:00
- [x] Remove maintenance mode @antonyharfield 
- [x] Announce launch is complete @naluinui
