### ISSUE TITLE
First launch feedback

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1544]
### Footer 
- [x]  [Help & Support](https://support.rfcx.org/) it should go to https://help.arbimon.org/

### Project (directory)
   - [x] When click in search box, there is an extra text came up (asd)
<img width="390" alt="Screenshot 2567-02-16 at 14 58 15" src="https://github.com/rfcx/arbimon/assets/87486094/759b7e33-b6af-430a-b27f-6051b50bf3b5">

- [x] Search: when delete search text, it seems to freeze on the last letter 
- [x] ~~When search for the project, it looks like the countries are disappeared in the project list (it could be slow loading)~~ _Deferred to #1557_

https://github.com/rfcx/arbimon/assets/87486094/744ce818-6b23-4124-b711-e50218b1e49c

- [x] Not show test site or site for external templates at 0,0 gps 
Project: https://arbimon.org/p/wwf-peru/insights
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708086473171729)

- [x] Not show this project on top of the project list https://arbimon.org/p/wwf-peru/insights
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708088219259519?thread_ts=1708086473.171729&cid=C04R9TT711U)

### Insights
- Owner can't  "Share Insights"
<img width="1403" alt="Screenshot 2567-02-16 at 15 58 06" src="https://github.com/rfcx/arbimon/assets/87486094/e7179627-5626-4ad4-8aba-7ac7966825a9">

- [x] ~~Species richness Map does not show up~~ Deferred to #1554 
<img width="1414" alt="Screenshot 2567-02-16 at 16 06 06" src="https://github.com/rfcx/arbimon/assets/87486094/65d751e3-8581-463c-8115-ff06d78d6a7a">

- [ ] Site with no detection should not show in blue dot
Project: https://arbimon.org/p/cofav2022/insights
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708089594731919) 
![image](https://github.com/rfcx/arbimon/assets/87486094/9345c4c2-d0e7-4e77-bbe1-6a3388a843fc)

#### Spotlight
- [x] ~~Map: not showing real species distribution~~ #1558 
Project: https://arbimon.org/p/puerto-rico-island-wide/insights/spotlight/accipiter-striatus-venator
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708088691704009)
![image](https://github.com/rfcx/arbimon/assets/87486094/fcb88fb3-cfce-45ee-a46e-d3995cdc845e)
Project: https://arbimon.org/p/bdffp-acoustics/insights/spotlight/accipiter-superciliosus
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708090053249299)

- [ ] Member of the project could not see LC species (unable to replicate)
Project: https://arbimon.org/p/bdffp-acoustics/insights/spotlight/accipiter-superciliosus
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708090053249299) 
![image](https://github.com/rfcx/arbimon/assets/87486094/77d61f30-6162-4ad0-8dd2-3bed95674f8c)

- [ ] When hover over the site, some of the sites don't show pop up with site name and detections frequency 
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708094235360449) 
Screen recording https://rfcx.slack.com/files/U019SQB5D0X/F06KKV62DUH/insights_page002.mp4

#### Stakeholders
- [x] ~~Make/remove primary contact should not show on top left of the screen~~ #1542 
<img width="846" alt="Screenshot 2567-02-16 at 17 09 41" src="https://github.com/rfcx/arbimon/assets/87486094/826d8921-480a-4828-9b86-4c0f37af45a6">

https://github.com/rfcx/arbimon/assets/87486094/cbb0932b-3c3d-4bf5-9a88-d789aac96554

### Site
- [x] Delete empty sites got the error message 
- [ ] Error communication error shows when import sites
Project: https://arbimon.org/p/costa-rica-abc-birdsplus-index/dashboard
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708091267141909)

### Account settings
- [ ] Profile image on the side bar and Member page are not the same (check account koonchaya.o@gmail.com)

https://github.com/rfcx/arbimon/assets/87486094/bebf0d6d-3fa4-457c-bbc7-e841f0bdb4e2

### My project
- [x] Refresh page after user delete the project and redirected to My project page (it showed the deleted project until reload the page)

### Safari
- [ ] fav icon
   <img width="348" alt="Screenshot 2567-02-16 at 11 00 46" src="https://github.com/rfcx/arbimon/assets/9149523/7802deb8-ac28-431c-a6b6-ec92f9c3113d">

### Homepage
- [x] “Learn More” button on the homepage should reset scroll position instead of taking you to the footer of “How it works” page. 
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708088945519409)
Screen recording 

https://github.com/rfcx/arbimon/assets/87486094/5dbac426-fd2e-4204-82be-fab13cf73b92
@naluinui We should do the same on https://arbimon.org/howitworks > Contact us 

https://github.com/rfcx/arbimon/assets/87486094/51c395b0-74a1-4b9d-8eb4-0f3c601d0f2a

- [ ] When I logged in and clicked About>Help&support>Contact us, it redirected to contact form but the My project and Profile went missing 

https://github.com/rfcx/arbimon/assets/87486094/8d606e18-5800-431d-ba0a-7e5205ad9d41

### Others
- [x] Redirect old link to new url for example https://arbimon.rfcx.org/project/jgi-rfcx-gombe-tz/dashboard
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708087835089009)
- [x] Redirect the link in all export files to new url 
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708091659685829)
- [x] Super user cannot open any projects. Ant is going to plan it in the future, not now
- [x] The map problem for some specific species
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708089017644209)
- [x] Visualizer: Time jumping when playing file on visualizer (I notice it happens after 10 seconds) and the position on the page also changes 
(Reported: https://rfcx.slack.com/archives/C04R9TT711U/p1708109977796229 , wendy.schackwitz@gmail.com)
https://rfcx.slack.com/files/U05R0KM0LUW/F06K64Z678D/gravac__a__o_de_tela_2024-02-16_a__s_15.50.25.mov
https://github.com/rfcx/arbimon/assets/87486094/6aead44f-79db-487c-87ca-97fbd6601e6b
