### ISSUE TITLE
My projects - user can search for projects by name

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1552]
## Background
https://rfcx.slack.com/archives/C04R9TT711U/p1708087835089009

User want an ability to search for projects so that they don't need to scroll down to find it.

<img width="753" alt="Screenshot 2567-02-20 at 10 24 48" src="https://github.com/rfcx/arbimon/assets/9149523/d7ced868-6552-4ad0-8072-799c0f12e94d">

## Alternatives
Add ability to access to your own private/unlisted project from the directory page

## Expected Outcome
- [ ] A search box that you can search for project by name

## Tasks
- [x] #1579 (separate ticket assigned)
- [x] UI: input box to search for project (placeholder text: search projects by name)
- [ ] UI: Search logic - search from pinia first, then fetch from API if necessary
