### ISSUE TITLE
Project directory map - improvements

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1555]
### Original discussion
https://rfcx.slack.com/archives/C04R9TT711U/p1708105835429219
https://rfcx.slack.com/archives/C04R9TT711U/p1708106072572149

### Tasks
- [x] when the user click open the pin from the map, keep the zoom level the same (do not zoom in further)
- [x] when the user click to close the project information popup, keep the zoom level the same (do not zoom out to the default)
- [x] grouping should be higher numbers (> 2 sites)
- [x] grouping label should change the maximum from 10+ to the nearest rounded number (10+, 20+, 30+, ..., 100+)

_Originally posted by @naluinui in https://github.com/rfcx/arbimon/issues/1544#issuecomment-1953788707_

Additional task from the previous sprint https://github.com/rfcx/arbimon/issues/1536#issuecomment-1953610911
