### ISSUE TITLE
Overview - update the number of sites to be all sites

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1559]
## Background
As a user, I want a way to see the summary of number of sites I created (originally raised here: [Kris](https://rfcx.slack.com/archives/C04R9TT711U/p1708091267141909), [Further discussion with team](https://rfcx.slack.com/archives/C02G4AR2GEL/p1708123340204279)

![Screenshot 2567-02-20 at 08 34 37 (2)](https://github.com/rfcx/arbimon/assets/9149523/e50d3ce3-96f4-457b-9e00-a705c792feea)

## Tasks
In overview (dashboard) page:
- [x] UI: use `store.projectFilters?.locationSites.length` as site count
- [x] Change "Sites created" description (i) from "Number of sites with recordings" to "Total sites created"
- [x] Map: make sure the number of pin shown in the map is the same amount as "sites created"
- [x] change url from `/dashboard` to `/overview`
