### ISSUE TITLE
Sprint Goal Q1-4 (22 Feb - 6 Mar)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1569]
## My project
🎯**Objectives**: User can search project name on My project
- [x] rfcx/arbimon#1552 
- [ ] rfcx/arbimon#1579 (good for first issue)

## Super users
🎯**Objectives**: Sci & support team can continue their workflow with access to partner / private projects
- [x] rfcx/arbimon#1545 
- [x] rfcx/arbimon#1546 
- [x] rfcx/arbimon#1553 

## Sync
🎯**Objectives**: Make sure all metrics sync correctly over the platform
- [x] rfcx/arbimon#1551
- [x] rfcx/arbimon#1556 
- [x] rfcx/arbimon#1557 
- [x] rfcx/arbimon#1559

#### Project (directory)
- [x] rfcx/arbimon#1513 
- [x] rfcx/arbimon#1577
- [x] rfcx/arbimon#1586
- [x] rfcx/arbimon#1587
- [x] rfcx/arbimon#1602
- [x] rfcx/arbimon#1588

#### Members
- [ ] rfcx/arbimon#1470

## UI reviews
🎯**Objectives**: New Arbimon improvements and bug fix
- [x] rfcx/arbimon#1555 
- [ ] rfcx/arbimon#1583 (good first issue)
- [ ] rfcx/arbimon#1565
- [x] rfcx/arbimon-legacy#1453 
- [x] rfcx/arbimon#1568
- [x] rfcx/arbimon-legacy#1451
- [x] rfcx/arbimon#1524
- [x] rfcx/arbimon-legacy#1477
- [x] rfcx/arbimon#1567
- [ ] rfcx/arbimon#1507
- [x] rfcx/arbimon#1580
- [x] rfcx/arbimon#1554
- [x] rfcx/arbimon#1612

## Quality
- [x] rfcx/arbimon#1575
- [x] rfcx/arbimon-legacy#1459
- [x] rfcx/arbimon#1547
- [x] rfcx/arbimon#1549

## Other
- [x] rfcx/arbimon-legacy#1444
- [x] rfcx/arbimon#1503
- [x] rfcx/arbimon#1537
- [x] https://github.com/rfcx/arbimon/issues/1541
- [ ] rfcx/arbimon-legacy#1455
- [x] rfcx/arbimon#1589
- [x] rfcx/arbimon#1591

## Uploader
- [x] rfcx/arbimon-uploader#206
- [x] rfcx/arbimon-uploader#202
- [x] rfcx/arbimon-uploader#204
- [x] rfcx/arbimon#1540 

### Layout fixing 
- [x] rfcx/arbimon#1570 
- [ ] rfcx/arbimon#1571 (good for first issue)

### Create CNN jobs
VDO https://drive.google.com/file/d/196uLXs9onVu9NmLfSA0hNFrQkRpXAUCM/view?usp=sharing
📸 Design: https://www.figma.com/file/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?type=design&node-id=24-157&mode=design&t=Aey8rwj2jlsPMZ5s-4
🎯 Objectives: User can create CNN jobs
- [x] rfcx/arbimon#1504

### Job summary
📸 Design: https://www.figma.com/file/FGnP9kAFLDmraAFJf8OBAG/CNN-Roadmap?type=design&node-id=97-810&mode=design&t=db84oLSZZkNFLZbs-4
🎯 **Objectives:** User can see CNN result summary (input, validation status, detected species, overall validating, job status)
- [x] rfcx/arbimon#1505
