### ISSUE TITLE
CNN Job create - fix site dropdown layout (overflowing)

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1570]
![image](https://github.com/rfcx/arbimon/assets/87486094/7573cbf9-fa0d-4b61-9002-b2dacebf53bf)

### Tasks
- [ ] Change element plus to use Flowbite

### Expected outcome (test cases)
- [ ] Can search for sites
- [ ] Can select all sites in the projects
- [ ] Can select 1 sites
- [ ] Can select multiple sites
- [ ] Can select sites beginning with keyword
- [ ] Dropdown disappeared when click outside
