### ISSUE TITLE
Member - show dialog after adding the users

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1583]
## Background

It's quite hard to see if you added the user in the project successfully without the dialog. Especially on a project that has a lot of members). 

Also, it's impossible to know that it failed.

### Step
1. open project with lots of member
2. add new user to a project (try name begin with 'z')
3. you then need to scroll to the end of the list to check if the new user appeared in the list

## Tasks 

Design https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=8426%3A5031&mode=design&t=Gpr0kfFW4JSQsKKl-1)

- [ ] Add dialog to show the status of the request (success or fail)

## Expected outcome
- [x] dialog show up when adding the user successfully (User added) 

![Image](https://github.com/rfcx/arbimon/assets/87486094/9b9959ad-8b07-4c20-9246-a646b33f4f83)

- [x] dialog show up when adding the user failed (Error - xxx) 

![Image](https://github.com/rfcx/arbimon/assets/87486094/e8f8a503-958c-472b-82a2-097186c02ff2)

- [x] dialog show up when adding the duplicate user 

![Image](https://github.com/rfcx/arbimon/assets/87486094/60f28228-1da9-4690-be23-beff49138495)

- [x] dialog disappear after 5 seconds
- [x] User can close the dialog before it disappear

Animation:
Click add member button, show toast to indicate action (Ease out, 400 ms)
Click “X” to close the toast (Ease out,  400 ms)
If user doesn’t click anything, the toast will fade out (Ease out, 700 ms) after a delay (7000ms)

_Originally posted by @naluinui in https://github.com/rfcx/arbimon/issues/1564#issuecomment-1960027419_
