### ISSUE TITLE
CNN - add test job so that we can test on dev or staging

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1601]
### Background

We don't have a way to test CNN flow in staging or dev

### Expected outcome
- [x] Can create jobs and see result running successfully
- [x] Can validate jobs

### Tasks
- [x] make sure the all APIs is working
