### ISSUE TITLE
🗂️ Epic - keep the species up to date

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1606]
### Background
The idea is to keep the species in our database up to date. 
We still need to find the way to keep species up to date.

This should be implement in the near future (next 1-2 sprint: by the end of Q2)\\

### 🗂️ Tasks
- [ ] Remove unused species from the database https://github.com/rfcx/arbimon/issues/1607
- [ ] Cross check Arbimon species name with IUCN & GBIF
- [ ] Flag species that in used but no data in GBIF
- [ ] Find duplicate species (synonym) and number of place that use this data

New feature
- [ ] Synonym ?
