### ISSUE TITLE
Limit project name and slug length

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#1627]
## Background
There was a partner project issue due to the long project slug. After they changed the name which is very long, the api did not work. So partner could not open the project. We fixed by editing the slug to be shorter. See discussion [here](https://rfcx.slack.com/archives/C04R9TT711U/p1709045126267529)

Long slug the user did manage to set
https://arbimon.org/api/projects/Fire-effects-on-bird-communities-from-seasonally-flooded-forests-along-Amazonian-black-water-rivers-of-the-Negro-River-basin

## Alternatives
We should have the limitation on how long user can name the project name and slug from
- Create a new project
- Edit the project name and slug from Project information

## Expected results
- [x] When creating projects, if the user enters a really long project name then limit the slug to 50 characters
- [x] When editing project settings, prevent the user from setting slug longer than 50 characters
- [x] When editing project settings, prevent the user from setting slug with invalid characters (valid => `a-z`, `0-9`, `-`, lowercase, not start or end with `-`)
- [x] After updating slug, user gets redirected to new url
- [x] Do not allow user to update slug that is not unique (test by trying to update a slug to be the same as another project)

## Tasks
- [x] API: POST `/project` project api should generate sensible slug (length + case sensitive)
- [x] API: PUT `/profile` should have limit how long the slug should be
- [x] WEB: Limit the slug length to match the API
- [x] WEB: Validate the slug `isValidSlug` and show error to use (and do not let the user submit unless slug is valid)
