### ISSUE TITLE
🗂️ Epic - Hide virtual or 0,0 sites from Insight reports & map

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1660]
Goal: [#1394](https://github.com/rfcx/arbimon/issues/1394)

## Plans to work towards

Legacy
- [ ] Legacy - inform user that site with 0,0 is a test site (won't be showing in report, map)

API
- [ ] Core API - when update location to 0,0 country should be updated to null

Sync
- [ ] Sync - exclude recording & detection number from virtual sites

Report
- [ ] exclude 0,0 or virtual sites from map (overview, insights, project directory)
- [ ] prevent user from publishing project insights on a project that only has test (virtual) sites
- [ ] update number of sites info description for both overview & insight page to reflect this change
