### ISSUE TITLE
🗂️ Epic - sync issue

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1679]
- [x] https://github.com/rfcx/engineering-support/issues/518
- [x] https://github.com/rfcx/arbimon/issues/1556
- [x] https://github.com/rfcx/engineering-support/issues/437
- [ ] Show last sync status in the insight page?
- [x] Go through `sync_error` table to investigate the problem happening in the past
- [x] Endpoint to call sync-fix by project
- [x] #1933
