### ISSUE TITLE
Change text of chart color

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#1700]
# Background

White text on bright yellow & orange has low contrast and difficult to read.

| Current | New color |
|--|--|
|![Screenshot 2567-03-11 at 23 02 49](https://github.com/rfcx/arbimon/assets/9149523/b5868816-a9ec-41ba-b928-b3d63e8c5772)|![Screenshot 2567-03-11 at 22 15 50](https://github.com/rfcx/arbimon/assets/9149523/badd746a-58d7-42a1-82a4-7be6e1afb24d)|

Tiffany proposed new charting color background and text as following
![Screenshot 2024-03-11 at 6 53 37 PM](https://github.com/rfcx/arbimon/assets/9149523/d16601b4-7c97-48f8-9331-05af67b6242d)

# Expected outcome
- [x] change `#008059` to be `#00543B`
- [x] change `#FF9457` to be `#FFA541`
- [ ] change color for ‘Regionally Extinct’ from `#444444` to be `#4B4B4B`
- [ ] change color for ‘Extinct in the Wild’ from `#222222 ` to be `#242424`
- [x] use text-insight `#FFFEFC` with palm `#00543B` & red `#A31A33` background
- [x] use text-pitch for the rest of the statuses
- [x] change text color on hover state of conservation status to be as following (for bright color that pair with text-pitch). For normal state, text will remain white
  ![Screenshot 2567-03-11 at 22 17 54](https://github.com/rfcx/arbimon/assets/9149523/8fd2e016-a71b-4228-b1cf-e70e2bb42dce)
