### ISSUE TITLE
Provide backup feature for projects

### ISSUE THREAD

**Issue by carlybatist** [rfcx/arbimon#1807]
### Context

From @carlybatist and Ant/Marconi -

We should have a way to provide partners with a backup of all their data from a project (all raw recordings, results of jobs they've run, all metadata, all Insights maps/figures). 

This feature will fulfill compliance with EU law (GDPR) - all users should (read: need to) have a way to download their data.

### Expected results

- [x] Project settings page is changed to 1 column layout as per design
- [x] Project settings contains "Project backup" section
- [x] "Request backup" is disabled if you are not a project owner (same as delete)
- [x] "Request backup" is disabled if there was a backup requested in the last 7 days
- [x] When the user presses "Request backup",  a new row shows up on the right with status "Requested"
- [x] The row changes from "Requested" to "In progress" when the job starts
- [x] Within 24 hours, the job is completed and shows "Success"
- [x] When the job is completed, an email is sent to the user containing the download link.
- [x] The link to the project backup expires after 7 days.
- [x] Only show the last 3 requests. Disable the expire link.
- [x] Any tables with a uri/url/file associated with them will have an S3 signed url generated (to enable programatic downloading) that will expire after 7 days
- [x] Project owner and Admin can make backup request

#### Additional notes

- The user cannot cancel or delete a backup

#### Design

https://www.figma.com/file/GjR3UAHkQyGvx1iZzdZdDw/%F0%9F%92%BB-Arbimon-Platform?type=design&node-id=9914-6375&mode=design&t=ZfYWta8cBYYoo7ts-4

Copy:
> You can request a comprehensive backup—including all raw recordings, job results, metadata, and Insights visuals—every 7 days. Once requested, your download link will be ready within 24 hours. Remember, download links expire after 7 days, so be sure to save your backup promptly.

### Proposed technical implementation

1. When the project admin/owner requests a backup, it adds a row to a new "backup" table containing `project id`, `requested by` (user), `requested at` (timestamp), `expires at` (timestamp), `status` (requested, processing, available), `url`, `size` (number of mbs).
2. After the user requests a backup, they will not be able to request another backup for 30 days. (to limit overuse of this feature)
3. Background job runs every night (middle of the night US time) that will pick up any requested backups and start processing them one at a time.
4. Backup process:
  - change status to `processing`
  - export sites.csv, species.csv
  - export recordings.csv (generating a signed url for each uri)
  - export playlists.csv, playlist_recordings.csv
  - export templates.csv (generating a signed url for each uri)
  - export recording_validations.csv
  - export pattern_matchings.csv, pattern_matching_rois.csv (generating a signed url for each uri), (maybe pattern_matching_validations.csv?)
  - export soundscapes.csv (generating a signed url for each uri)
  _- export classifications.csv, model_training.csv (maybe training_set.csv)?_
  _- export AED.csv, clustering.csv_
  - zip all csv files, upload to S3 export folder
  - change status to `available`
  - send email to requesting user that the backup is available with the link in the email

## Related APIs
- [x] Set up new database table to store backup data (#1903)
- [x] Backup - `GET` backup history list (by project id) (#1903)
- [x] Backup - `POST` backup to create a new backup request (#1903)
- [x] #1904 

## Other related tasks
- [ ] [Publish python script to download all files from backup csv](https://github.com/rfcx/arbimon/issues/1943)
