### ISSUE TITLE
Update new Arbimon database checklist

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2108]
Backend
- [ ] https://github.com/rfcx/arbimon-db-migration

Frontend
- [ ] Maintenance page
- [ ] Uploader error message

Testing
- Arbimon
  - [ ] Create a new project
  - [ ] Check created project
  - [ ] Check all legacy pages
- Legacy
  - [ ] Create a new site
  - [ ] Check created site on the page
- PM
  - [ ] Upload recordings
  - [ ] Create a new template
  - [ ] Create a new playlist
  - [ ] Create PM job
  - [ ] Check job on Active job page
  - [ ] Check rois result, you can see roi image.
- AED
  - [ ] Create a new AED job
  - [ ] Check job on Active job page
  - [ ] Check result 
- Clustering
  - [ ] Create a new clustering job
  - [ ] Check job on Active job page
  - [ ] Check result
  - [ ] Check detail on grid view. Check rois result, you can see roi image.
- Settings
  - [ ]  Check settings page

**Comment by koonchaya** [comment]
During migration
![Image](https://github.com/user-attachments/assets/306b8a31-329b-45ac-8115-c84038972fff)
![Image](https://github.com/user-attachments/assets/16f2ebb2-f894-414d-ba02-35df6284ef5b)
