### ISSUE TITLE
Q1 / Sprint 5 / Goal 3: Sync history epic

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#629]
Outcome:
- [ ] The app should constantly sync "only changed" data from Arbimon every hour
- [ ] The user should see the last sync time on the Dashboard page
- [ ] The user should see a list of sync dates in a new sync history page
