### ISSUE TITLE
Sync - The app should constantly sync "only changed" data from Arbimon every hour

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#631]
### 📇  Business requirements

The app should automatically sync data from Arbimon every hour -- so that the latest version of the report, always in sync with validated data from Arbimon

### ⚙️  Implementation Requirements
- Only query what has changed
- Remove what is not anymore exist
- Write/Update the changes to the database
- Make the crons flexible to get single & multiple projects

## Tasks
- [x] Update script to sync data for a project every hour
- [x] ~~Update Arbimon SQL query to only get data that updated_at after our last updated at~~ _Cancelled as the current schema of Arbimon table is not supported_
- [x] Update detection script to delete what is not exist
- [x] #655
- [x] #656
