### ISSUE TITLE
Versions - Update project-selector (to respect ProjectVersion)

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#660]
## Questions

- The navigation logic implies loading the ProjectVersion list *before* navigating. We could pre-load the latest version during the `/projects` API, but this risks it being out-of-date when switching project, and sending the user to, ex: the 2nd newest published version. Is this accceptable?

## Outcome

Update the project selector to have separate sections:
- "My projects" = any project where the current user is a team member
- "Public projects" = any project where:
   - user is NOT a team-member (covered above)
   - has 1+ ProjectVersion that is BOTH published AND public

## Sub-Tasks

This PBI includes:
- [x] Update the project-selector UI
- [x] Update the /projects API (response type & implementation) (if necessary / not already done)
- [ ] When selecting a project...
  - If the project mode is currently "draft" AND the user is a team member for the newly selected project => maintain the project mode as "draft"
  - Else change the project mode to the most recent "published" version
- [ ] Ensure that a user without access sees an error message

## Exclusions (not included in this PBI)

- Cache the user's project's in Bio DB for faster permissions checks
