### ISSUE TITLE
Versions - Version selector

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#664]
## Questions

- Can we think of better words for the named versions?
  - Draft? Latest? Live? Sync'd? Recent? Unpublished? Future?
  - Published? Latest Published? Current?
- Display only to the logged in user and is a team member?

## Outcome

Add a version selector to the navbar:
https://www.figma.com/file/NMJroXnbMwWqbfeDResV5s/Design---BioWeb-x-CNN-workflow

![Screen Shot 2022-03-17 at 13 06 45](https://user-images.githubusercontent.com/31621095/158747535-e3a27e28-ae89-487e-b7de-f1344435c71b.png)

## Sub-Tasks

- [x] UI for selector
  - If there are no published versions, should we show "Latest Published" greyed out & unclickable
- [ ] Change the route when a different version is click, **maintaining the current page!**
  - #665
- [x] Load the selected project's versions into Pinia

## Exclusions (not included in this PBI)

- Only implement "Draft" & "Latest Published" -- Version History will be done in #670
