### ISSUE TITLE
Pub-Flow - Publish action

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#666]
## Questions

- Should the publish action include creating the new draft ProjectVersion & DataSource (containing the same data as the recently published version)?
  - Pro: Simplifies sync job (eliminates a case that can only occur after publish)
  - Con: Makes it harder to check whether a draft contains new data (i.e. can it be published?) -- if we don't create a new version, the "draft" PV will be the exact same object as the published PV, and will have isPublished=true, preventing re-publishing
- Why not control Arbimon link visibility by `isProjectMember` state?

## Outcome

User can click "publish" to create a new frozen snapshot of their data

![Screen Shot 2022-03-17 at 13 00 30](https://user-images.githubusercontent.com/31621095/158746679-05f3c21c-569c-45ea-b6ac-f908d1f20ee7.png)

![Screen Shot 2022-03-17 at 16 15 03](https://user-images.githubusercontent.com/31621095/158776809-070f6225-f264-40d9-91f7-4b5512e80568.png)

## Sub-Tasks

- [ ] Open modal when "publish" is clicked
  - **Please put "Anyone" first, and check it by default**
- [ ] Update ProjectVersion type/model/migration/seed/sync to add new fields (isPublic: true/false; isDownloadAllowed: true/false; isArbimonLinkShown: true/false)
- [ ] An idempotent API: `POST` `/projects/:project-id/versions/:version-id/publish` the publishes that version, or does nothing if it's already published
  - Send the data from the modal in the query string
  - Use the ProjectVersion model to update it in the DB, setting `isPublished: true` & saving above data
