### ISSUE TITLE
All Projects - Update `/projects` API to respect `isProjectMember`

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#672]
## Outcome

After this PBI is finished:
- All projects will be visible to their team members (auto-sync'd latest draft data)
- No project will be public

## Sub-Tasks

- [x] Get list of projects from core API where they are a team member
- [x] Sync all projects (not just "isPublished")
- [x] Clean up: delete `isPublished` from LocationProject

**Note: they must be a team member; it is NOT sufficient for the project to be public**

## Optional

- [x] Cache permissions
- [ ] Update the /projects response type so that it includes whether the user is a team member (either `isProjectMember` or 2 lists) => supports #660

## Exclusions (not included in this PBI)

- Cannot publish
