### ISSUE TITLE
Release version 1 - Support all projects in "draft" mode (without ProjectVersion)

### ISSUE THREAD

**Issue by Nutto55** [rfcx/arbimon#690]
### Goals

https://www.figma.com/file/VUpCJD3VYIsBM3RljkWoSh/Release-plan-(publishing-version)?node-id=0%3A1
![Screen Shot 2022-03-29 at 11 14 27](https://user-images.githubusercontent.com/31621095/160531947-20fa4b4b-fb94-4635-954b-2cb25102f0db.png)

### Tasks
- [x] **End users only can see live / latest sync data from Arbimon (no versioning)**
  - [x] Hide version control
  - [x] Hide draft banner
- [x] **End users can see our showcase reports (BCI, Puerto Rico, etc)**
- [x] **Logged in users can see reports for their own projects**
  - [x] Add a sync job to CI that runs a full sync (Arbimon + IUCN + Wiki) -- do not wait for this job to finish!
  - [x] Test sync job if it sync user project correctly
- [x] **Logged in users can see sync history of their own projects**
  - [x] Hide sync history button if not a project user
- [x] Tweak project selector styles
  - [x] Title should be `text-xl`
  - [x] Remove padding from modal & add balanced padding to contents
  - [x] Don't put the selected project first
  - [x] Remove dotted line
