### ISSUE TITLE
Loading - Merge loading-state branch (from Mob)

### ISSUE THREAD

**Issue by Nutto55** [rfcx/arbimon#732]
# Outcome

- Manage `projectData` & `selectedProject` as stateful (ex: loading vs error vs data) objects
- Don't break anything :)

# Tasks

## Phase 1: Migrate Pinia state to use `useQuery`

Convert `projectFilters` state to `projectData` useQuery getter
- [x] Add `projectData` getter (that does the work of `projectFilters`
- [x] Push code from mob
- [x] Update all references to `projectData` (destructure states)

Convert `selectedProject` state to `selectedProjectSlug` state & `selectedProject` getter
- [x] Add `selectedProjectSlug` to state (to track the user-driven part of the selectedProject data)
- [x] Add `selectedProject` getter function that finds the project matching the `selectedProjectSlug`
- [x] Add `updateSelectedProjectSlug`
- [x] Update all references to `selectedProject` (destructure states) AND replace references to `updateSelectedProject` with `updatedSelectedProjectSlug`

Cleanup
- [x] Delete old state `projectFilters` and `selectedProject` in Pinia
- [x] Delete old actions `updateSelectedProject` and `updateProjectFilters` in Pinia
- [x] Open PR & request review => notify @nalui-nui @charles-allen

Example `setup()` in `vue-class-component`
```
const setup = setup(() => {
  // setup goes here
})
```

- [ ] Check that all pages and functionality work, **especially the comparison list and modal**
  - Fix bug when saving filters (#747 will help)
