### ISSUE TITLE
Loading - Refactor Filters

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#747]
# Outcome

- Simplify comparison-filter & comparison-filter-modal, to make it easier to fix an issue discovered in #732

# Tasks

- [x] Update prop names in `FilterDatasetQuery` (see below)

```ts
export interface FilterDatasetQuery extends QueryString {
  dateStartLocal: string
  dateEndLocal: string
  siteIds: string[] | string
  taxonClassIds: string[] | string
}
```

- [x] Add `DetectionFilter` with explicit & clean prop names/types (see below)
  - Add explicit `taxonClasses`
  - Delete `otherFilters`
  - Delete `FilterPropertyEquals`

```ts
export interface DetectionFilterSiteGroup {
  label: string
  sites: Site[]
}

export interface DetectionFilter {
  dateStartLocal: Dayjs
  dateEndLocal: Dayjs
  siteGroups: DetectionFilterSiteGroup[]
  taxonClasses: TaxonClass[]
}
```

- [x] Delete `ColoredFilter`, `ComparisonFilter`, `DatasetParameters`, `FilterImpl`; replace with `DetectionFilter`, and update references:
  - filterToDataset, generateFilterQuery
  - species richness, activity overview, spotlight
  - comparison list, map data, export data for map
  - etc

```ts
export function detectionFilterToDatasetQuery (filter: DetectionFilter): FilterDatasetQuery {
  return {
    dateStartLocal: filter.dateStartLocal.toISOString(),
    dateEndLocal: filter.dateEndLocal.toISOString(),
    siteIds: filter.siteGroups.flatMap((siteGroup) => siteGroup.sites.map(s => s.id.toString())),
    taxonClassIds: filter.taxonClasses.map(tc => tc.id.toString())
  }
}
```

- [x] Extract comparison-filter panels to separate components, ex: `filter-modal-panel-sites.vue`
- [x] Rename `comparison-list` => `filter-list`; `comparison-filter-modal` => `filter-modal`
- [x] Test properly

# Exclude

- Currently the API is called repeatedly for *all* filters after every filter change -- you don't need to fix leave this behavior (we will fix it in #736)
