### ISSUE TITLE
Sprint Goal Q2-6 (220609-220622)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#782]
# Goal: Complete CNN web flow

Increments:
1. Scheduling & Progress
2. User Experience & Expectations
3. Frontend Loading Issues & Performance

Capacity:
- @antonyharfield 40% (Wed 15 - Fri 24)
- @charles-allen 90% (Thu 16 PM, Fri 17 AM)
- @naluinui 80% (Fri 10 AM, Mon 13, Tue 14 PM)
- @rassokhina-e 90% (Mon 13)

TODO: Should we schedule issues from https://github.com/orgs/rfcx/projects/10?

-----

## Increment 1: Scheduling & Progress
@Nutto55 @antonyharfield @charles-allen

### Outcome

- Jobs scheduled from the web UI will be picked up & executed on Kubernetes
- Job progress will be reported periodically from the CLI & displayed on the web UI

### Why?

- Exposes CNN analysis to end-users

### PBIs

- [ ] rfcx/prediction-service#86 @Nutto55 
  - [x] rfcx/rfcx-api#375 @antonyharfield 
- [x] rfcx/prediction-service#85 @Nutto55 
  - [x] rfcx/rfcx-api/issues/373 @Nutto55 
  - [x] rfcx/rfcx-api#382 @charles-allen 
  - [x] rfcx/rfcx-api#380 @charles-allen 
- [x] rfcx/prediction-service#88 @Nutto55 
  - [x] rfcx/rfcx-api#380 @charles-allen (same API as above)

### Deferred Work / Ideas

- Prediction deployer checks for stalled jobs, kills the k8s job and marks them stalled
- Refresh button to update job progress
- Auto-refresh

-----

## Increment 2: Submit CNN Jobs from Web UI
@naluinui @rassokhina-e 

### Outcome

- User can submit a CNN job from the web UI
- User can see submitted jobs in the list UI

### Why?
- Enable users to queue the CNN Job easier with the Web Interface

### Process

<img width="1436" alt="Screen Shot 2565-06-14 at 09 27 13" src="https://user-images.githubusercontent.com/9149523/173480548-d61f008b-5e60-4680-be98-30c47f28db04.png">

### Exclusions / Limitations
- Ability to review job size (Step 3)

### PBIs

- [x] Merge existing Core API PR
- [ ] Job create screen (#771 )  @naluinui @rassokhina-e 
  - [x] rfcx/biodiversity-analytics#797
  - [x] rfcx/biodiversity-analytics#790 @rassokhina-e 
  - [x] rfcx/biodiversity-analytics#791 @naluinui 
  - [x] rfcx/biodiversity-analytics#792 @naluinui 
  - [x] rfcx/biodiversity-analytics#793 @naluinui 
  - [x] rfcx/biodiversity-analytics#794 @rassokhina-e 
- [x] Job list screen @rassokhina-e @naluinui 
  - [x] Update `GET /classifiers` to only show classifiers that are `is_public` OR `created_by` the user
  - [x] rfcx/biodiversity-analytics#772 @rassokhina-e 
  - [x] Bonus: rfcx/biodiversity-analytics#796 @rassokhina-e 
- [x] Unified nav @naluinui @rassokhina-e 
  - [x] Side bar should be stick to the left from top to bottom
  - [ ] Side bar should be working better in smaller screen
- [ ] Helper @charles-allen 
  - [ ] Lift up useful/workable chuck of code from loadable branch
  - [x] Support component testing

### Deferred Work / Ideas

- My jobs (all CNN jobs created by the user in all projects)

-----

## Increment 3: Frontend Loading Issues & Performance
@charles-allen 

### Outcome

- TODO

### Why?

- TODO

### Process

- TODO

### Exclusions / Limitations

- TODO

### PBIs

- [ ] Fix loading issues
  - [x] rfcx/biodiversity-analytics#779
  - [ ] rfcx/biodiversity-analytics#740
- [ ] Display loading state (ex: spinners)

### Deferred Work / Ideas

- Investigate performance improvements
  - Avoid network waterfalls
  - Code-splitting
  - Tree-shaking
  - Leaner builds (split packages & only include needed packages)
  - Caches

-----

### Outcome

- TODO

### Why?

- TODO

### Process

- TODO

### Exclusions / Limitations

- TODO

### PBIs

- [ ] TODO

### Deferred Work / Ideas

- TODO

-----

### Outcome

- TODO

### Why?

- TODO

### Process

- TODO

### Exclusions / Limitations

- TODO

### PBIs

- [ ] rfcx/biodiversity-analytics#778

### Deferred Work / Ideas

- TODO

-----

## Outcome

- User gets feedback on estimated wait time (queue + processing)
- User gets feedback on the current status of in-work jobs

### PBIs

- [ ] Show number of waiting jobs
  - [ ] `GET /classifier-jobs/waiting-count` -- return total number of waiting jobs across all projects & all users
  - [ ] UI
- [ ] Show estimated job size in minutes of audio (e.g. 50,000 minutes, to nearest 10,000), updated when the filters change
  - [ ] New Core/Reporting endpoint returning estimate number of minutes (not number of segments)
  - [ ] UI
- [ ] Show estimated processing time (if avg performance available on classifier)
  - [ ] Add nullable columns "mean_processing_rate" (minutes spent processing per minute of input audio) and "sd_processing_rate" to `classifiers` table
  - [ ] UI for unknown case
  - [ ] UI for known case: rounded (minutes * mean_processing_rate) +/- 1 sd range
- [ ] Enforce maximum job size: 250,000 minutes (~1 month x 50 sites x 1:5 sampling ratio)
