### ISSUE TITLE
[Sprint Q2-7][Goal 4.1] Incremental Sync

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#810]
## Increment 4.1: Update Sync
@charles-allen @rassokhina-e @naluinui @Nutto55

#### Outcome
- Have recordings summary in Report DB (ready for increment 2)
- Improve sync mechanism https://github.com/rfcx/engineering-support/issues/33

#### Flow
https://docs.google.com/presentation/d/16TLsxvWooZkx8-vfHW3yr2IoYywsdcpSHHigLPkyBCg/edit#slide=id.g134b77d72c8_0_303

#### Tasks
- [x] https://github.com/rfcx/arbimon/issues/949
- [x] #802 @naluinui 
  - [x] Tests for outputs/sync-error & outputs/sync-status @rassokhina-e 
  - [x] Add lon/lat to project sync @naluinui 
  - [x] Migration to remove `slug_arbimon` (& set lon/lat defaults??) @naluinui 
  - [x] Test: sync Arbimon `staging` to Bio `local` @rassokhina-e 
  - [x] Kubernetes cron config for incremental sync @naluinui 
- [x] #805 @rassokhina-e 
- [x] #804 @naluinui 
- [x] #806 @rassokhina-e 
- [x] #816 @Nutto55 
- [x] #829 @rassokhina-e 

Supporting:

- [x] Upgrade parsing to include original data @charles-allen 
- [x] Work out how to ensure `idArbimon` exists when parsing fails @charles-allen 
- [x] Update test scripts (ex: cross-env, check rms isn't seeding data) @charles-allen 
- [x] Document how to run integration tests @charles-allen 
- [x] Document how to use `--mode` to sync Arbimon staging > Bio local @charles-allen 
- [x] Cleanup Bio DB after tests (make sure this doesn't conflict with API tests) @charles-allen 
- [x] ~~Fix Sequelize model PropsCreate (ex: optional lon, lat, etc)~~ @charles-allen 

Deferred:
- [ ] #808
- Track "resolved" status of error logs (ex: check them off when they sync successfully at a later date)
- Ensure `console.error` is called if error count > 0
