### ISSUE TITLE
[Sprint Q2-7][Goal 4.2] CNN Job Estimation

### ISSUE THREAD

**Issue by charles-allen** [rfcx/arbimon#811]
## Increment 4.2: CNN Job Estimation
@rassokhina-e @naluinui @Nutto55

- [x] rfcx/prediction-service#91
  - [x] Remove the logic to get all segments at once from CLI 
- [x] rfcx/biodiversity-analytics#832
![image](https://user-images.githubusercontent.com/44169425/177716015-fee14172-a2b2-4616-9340-2f7d309bb69f.png)
- [x] rfcx/biodiversity-analytics#833
  - [x] Change `recordings` to `duration of recordings`
