### ISSUE TITLE
CNN V1 Improvements

### ISSUE THREAD

**Issue by naluinui** [rfcx/arbimon#820]
## CNN V1 Improvements
- [x] rfcx/biodiversity-analytics#825
- [x] rfcx/biodiversity-analytics#822
- [x] rfcx/biodiversity-analytics#824
- [x] rfcx/prediction-service#90

_Originally posted by @naluinui in https://github.com/rfcx/biodiversity-analytics/issues/817#issuecomment-1176134304_
