### ISSUE TITLE
Sprint Goal Q3-3 (20220804-20220817)

### ISSUE THREAD

**Issue by Nutto55** [rfcx/arbimon#845]
### 1. Setup new staging+test environment (Arbimon+Bio) @antonyharfield @rassokhina-e 
- [x] Setup testing and staging db for Arbimon (keep Rooftop, BCI, ??)
- [x] Setup testing and staging db for Bio
  - [x] Update bio cli secrets in Kubernetes
  - [x] Update bio cli secrets file in one password
- [ ] Successfully run the sync without db down: _In Progress - sync recordings_

### 2. Incremental sync (Bio) @rassokhina-e @Nutto55 
- [x] rfcx/biodiversity-analytics#830
- [ ] Launch it to the staging and production: _In Progress - on the staging now_

### 3. User support @rassokhina-e @Nutto55 @koonchaya 
- [x] https://github.com/rfcx/engineering-support/issues/92 @rassokhina-e 
- [x] https://github.com/rfcx/engineering-support/issues/98 @antonyharfield 
- [x] https://github.com/rfcx/engineering-support/issues/35 @rassokhina-e  
- [x] https://github.com/rfcx/engineering-support/issues/65 @rassokhina-e @Nutto55 
- [x] https://github.com/rfcx/engineering-support/issues/95 @rassokhina-e @Nutto55 
- [x] https://github.com/rfcx/engineering-support/issues/99 @rassokhina-e 
- [x] [Export a list with all species identified in Arbimon](https://github.com/rfcx/engineering-support/issues/93) @rassokhina-e 
- [x] Get list of validated species @naluinui @rassokhina-e 
- [x] Fix Uploader's tasks @naluinui 

### 4. Clustering tweaks @rassokhina-e @koonchaya 
- [x] Clustering jobs appear in the job list even if they error
- [x] If the min frequency of an AED is 0, it shows as “(missing)” in the Grid View page
- [x] Remove the dropdown to select between LDA and UMAP. Using the default LDA for the display, with no option to change

#### Design
- [x] Deliver paper prototype/wireframe
- [x] Get feedback from stakeholders

#### Integrate with SDK to enable authentication
- [x] rfcx/rfcx-sdk-python#18
- [x] rfcx/prediction-service#93

#### Publicly publishable (remove dependencies on AWS/Auth0 secrets)
- [x] Refactor to support client secret and login via SDK
- [ ] Public the image to docker hub
  - [ ] Clean up the docker file to include only related file
- [ ] Update documentation

### 7. Meta data for projects @antonyharfield @koonchaya 
- [x] Have a meeting and define requirements 

**Capacity:**
@Nutto55 5.5/9 (Thu 11 - Tue 16)
@koonchaya 8.5/9 (Fri 12)

---
#### CLI/Prediction service/Prediction deployer
- [ ] Remove AWS config from prediction deployer
- [ ] Remove any remaining AWS secret/key code on (config.py) prediction service
- [ ] Support prediction service batch job with arguments
- [ ] Update the prediction deployer and prediction services relied on new env structures (template to create classifier)
- [ ] Public the prediction service 
  - [ ] Auth0 id and secret
  - [ ] Docker should include only related files 

#### Core API
- [ ] Support get project by project name/project slug (core api)
- [ ] Support segment to query by `query_hours`
- [ ] PATCH /classifiers/:id support update the classifications
- [ ] Delete `deployment_parameters` column in `classifier_deployment` table (can leave it as null value)
  -  Use ignore_threshold from classifier_outputs to get the minimum confidence instead
  - Decide what to do with the step_seconds

#### Python SDK
- [x] Research the login flow for SDK
- [ ] Consider about which part of SDK can use in prediction service
  - [ ] List out what have in SDK that can use in prediction service
- [ ] Update or delete examples

#### Bio web
- [ ] Support query site name with `*` in create job page
- [ ] Site selector should not have clear all icon at the end of selector
- [ ] Update date selector UI in CNN create page
- [ ] Migrate project table
  - [ ] Consider if we use `country` and `state` from core project table
- [ ] Clear default sites when add comparison
- [ ] Remember comparison when switch page
- [ ] Update site filter in comparison modal to allow any match substring
- [ ] Hang the footer at the bottom of all pages
- [ ] In job size estimation showed no response text when there is an error. I think we could use better text.
- [ ] When user select "all sites in the project", the sites dropdown should be close after selected.
- [ ] User should not be able to select future date
- [ ] When select Custom (time of day), this should not allow to put start time later than end time e.g. 10-5
- [ ] Check all the wiki fields for `photo_url`
- [ ] Knowledge sharing for the html tag with @koonchaya 

#### Bio API & Bio CLI
- [ ] Add POST /projects/:id/profile for updating project information e.g. summaryText, readme
- [ ] Delete legacy tables
  - [ ] `detection-by-site-hour` (model)
  - [ ] `data-source`
  - [ ]  ...
- [ ] Pick up test cases for spotlight and activity api from `mob-project-sync` branch to dev branch 
- [ ] Investigate `photo_url` is too long cause database failed issue
- [ ] rfcx/biodiversity-analytics#808
- [ ] Apply Kubernetes secret from CD instead of do it manually

#### Error alert
- [ ] Update Grafana to send only useful error alert e.g. error with 500 status
