### ISSUE TITLE
Sprint Goal Q3-5 (20220901-20220914)

### ISSUE THREAD

**Issue by Nutto55** [rfcx/arbimon#857]
## Quality: integrity and performance (OKR2) @rassokhina-e @antonyharfield 
- [ ] Report integrity (correct data)
  - [x] #870
  - [x] Add support for deleting detections
     - [x] rfcx/arbimon#1025
     - [x] #877
  - [ ] Add support for deleting recordings
     - [x] rfcx/arbimon#1023
     - [x] rfcx/arbimon#1024
     - [x] #869
  - [x] #878
  - [x] #852
  - [x] #879
  - [ ] #880
- [ ] Production performance testing
  - [x] #871
  - [x] #872

## Species validation (OKR2) @Nutto55 @naluinui 
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## User support @koonchaya @rassokhina-e @Nutto55 @antonyharfield 
- [x] https://github.com/rfcx/engineering-support/issues/123
- [x] Limit playlist size for acoustic and detector analysis (audio clustering jobs)
- [x] https://github.com/rfcx/engineering-support/issues/119
- [x] https://github.com/rfcx/engineering-support/issues/127
- [x] https://github.com/rfcx/arbimon/issues/1069
- [ ] https://github.com/rfcx/engineering-support/issues/76 - blocked: found duplicate rows that need merging and add unique keys
- [x] https://github.com/rfcx/engineering-support/issues/117 - waiting to release

## Arbimon performance (OKR4) @rassokhina-e 
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
