### ISSUE TITLE
Update sync (and write tests) to check for deleted recordings after updated recordings

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#869]
### Requirements
- Int tests to document cases where recordings are deleted
  - `recorded_minutes` array and `count_of_recorded_minutes` is updated after delete
  - `recorded_minutes` array should support recordings less than 1 minute

### Notes
- Consider changing `recorded_minutes` array to be a count of the number of recordings in that minute. E.g. `[0,1,0,2,...]` is 1 recording in the 2nd minute, 2 recordings in the 4th minute, etc.
- Assume recordings are always 1 minute or less
- Use the `start` of the recording to determine the bucket (don't consider start and end time and the span across minute boundaries - discussed with Jack that this is a sensible assumption)

### Sub-tasks
- [ ] Change `recorded_minutes` into the format of 60 mins array
- [ ] Change column name to `count_of_recorded_minutes` and a logic to count number of recordings in 60 mins period
- [ ] Detect deleted recording from a `deleted_recordings` table in Arbimon
