### ISSUE TITLE
Sprint Goal Q3-6 (15 Sep - 28 Sep 2022)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#882]
## Song Meter support
To support the use of SongMeter deployment with RFCx Companion
- [x] Uploader 
  - [x] https://github.com/rfcx/ingest-app/issues/172
  - [x] https://github.com/rfcx/ingest-app/issues/171
  - [x] https://github.com/rfcx/ingest-app/issues/170
  - [x] https://github.com/rfcx/ingest-app/issues/169
- [x] Arbimon
  - [x] rfcx/arbimon#1055

## Arbimon Insights user journey
- [x] rfcx/arbimon#1040
- [x] rfcx/biodiversity-analytics#885
- [x] rfcx/arbimon#1039
- [ ] rfcx/biodiversity-analytics#896

## User support @koonchaya @rassokhina-e @Nutto55 @antonyharfield 
- [x] rfcx/engineering-support#76 
- [x] rfcx/arbimon#1041
- [ ] Web uploader
  - [x] rfcx/engineering-support#136 ("keep waiting")
  - [ ] rfcx/arbimon#1069  (re-uploading)
  - [x] rfcx/arbimon#1056
- [x] rfcx/engineering-support#132
- [x] rfcx/biodiversity-analytics#898
- [x] rfcx/engineering-support#138

## Quality: integrity and performance (OKR2) @rassokhina-e @antonyharfield 
- [ ] Report integrity (correct data)
  - [ ] Add support for deleting recordings
     - [x] rfcx/arbimon#1024
     - [x] rfcx/biodiversity-analytics#869
  - [x] rfcx/biodiversity-analytics#878
  - [x] rfcx/biodiversity-analytics#852
  - [ ] rfcx/biodiversity-analytics#880
- [ ] Production performance testing
  - [x] rfcx/biodiversity-analytics#871
  - [x] rfcx/biodiversity-analytics#872
- [x] rfcx/arbimon#1042
- [x] rfcx/rfcx-sdk-python#21

---
_Not included in the sprint goal, but still tracking..._

## Species validation (OKR2) @Nutto55 @naluinui 
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## Arbimon performance (OKR4) @rassokhina-e 
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
