### ISSUE TITLE
Sprint Goal Q3-7 (29 Sep - 12 Oct 2022)

### ISSUE THREAD

**Issue by Nutto55** [rfcx/arbimon#901]
## 1. Song Meter support @naluinui @koonchaya 
- [x] rfcx/biodiversity-analytics#902
- [x] Add Arbimon metadata shows “Song Meter”
  - [x] rfcx/ingest-app#173
  - [x] rfcx/ingest-service#45
  - [x] rfcx/arbimon#1057
- [x] rfcx/biodiversity-analytics#906
- [x] Launch Uploader
- [x] Launch Companion

## 2. User support @antonyharfield @Nutto55 @rassokhina-e 
- [x] rfcx/engineering-support#146
- [x] rfcx/arbimon#1056
- [x] rfcx/arbimon#1069
- [x] rfcx/arbimon#1054
- [x] Audio clustering
  - [x] rfcx/arbimon#1058
  - [x] rfcx/arbimon#1059
- [x] rfcx/arbimon#1060
- [x] Give a GitHub access to Marconi account
- [x] rfcx/engineering-support#131

## 3. Quality @antonyharfield @Nutto55 
- [x] Report integrity (correct data)
  - [x] Add support for deleting recordings
     - [x] rfcx/arbimon#1024
     - [x] #869
  - [x] #910
  - [x] #912
- [ ] Production performance testing
  - [x] #871
  - [x] #911
  - [x] #872
- [x] rfcx/arbimon#1042
- [ ] #880

## 4. Heatmap on Arbimon-Insights @Nutto55 
- [x] #913
![image](https://user-images.githubusercontent.com/44169425/192987766-7abfe21c-b086-4401-a475-75453f225bcb.png)

## 5. User research @tiffanylee0125 
- [x] Conduct user interviews (5-10 ppl) with external scientists
- [x] Usability testing with internal scientists
- [ ] Create 3-5 personas + empathy maps for various user group

---
_Not included in the sprint goal, but still tracking..._

## Species validation (OKR2) @Nutto55 @naluinui 
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## Arbimon performance (OKR4) @rassokhina-e 
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
