### ISSUE TITLE
Sprint Goal Q4-1 (13 - 26 Oct 2022)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#915]
## 1. AED and Clustering @rassokhina-e 
- [x] rfcx/arbimon#1087
- [x] rfcx/arbimon#1088
- [x] rfcx/arbimon#1089

## 2. Heatmap on Arbimon-Insights @Nutto55 
- [x] rfcx/biodiversity-analytics#913
- [ ] rfcx/biodiversity-analytics#916 - Cancelled - doesn't make sense for heat map
- [x] rfcx/biodiversity-analytics#917

## 3. Soundscapes @antonyharfield
- [ ] rfcx/arbimon-soundscapes#1
- [ ] rfcx/arbimon-soundscapes#2

## 4. User support @koonchaya  @rassokhina-e @Nutto55 
- [x] rfcx/engineering-support#140
- [x] rfcx/engineering-support#163
- [x] [Create template/tag does not show pop up when zoomed in](https://github.com/rfcx/engineering-support/issues/171)
- [x] rfcx/engineering-support#149

## 5. User research @tiffanylee0125 
- [ ] Interview insights synthesis & shareback
- [ ] 3 personas & empathy maps 
- [ ] Treejack test for navigation titles

## 6. Quality @antonyharfield @Nutto55 @koonchaya 
- [x] Production performance testing
  - [x] rfcx/biodiversity-analytics#911
  - [x] rfcx/biodiversity-analytics#872
- [x] rfcx/arbimon#1042
- [ ] rfcx/biodiversity-analytics#880
- [x] rfcx/biodiversity-analytics#918

## 7. Web-Uploader performance @rassokhina-e 
- [ ] #924 [ON THE STAGING NOW]

----

_Backup: Not included in the sprint goal, but still tracking..._

## Species validation
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## Arbimon performance
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
