### ISSUE TITLE
Sprint Goal Q4-2 (27 Oct - 9 Nov 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#925]
## 1. AED and Clustering @rassokhina-e 
- [x] rfcx/arbimon#1095 
- [x] rfcx/arbimon#1096 __ON STAGING NOW__
- [x] rfcx/arbimon#1097 __ON STAGING NOW__

## 2. Soundscapes @antonyharfield
- [x] rfcx/arbimon-soundscapes#1
- [x] rfcx/arbimon-soundscapes#2

## 3. User support @koonchaya  @rassokhina-e @antonyharfield
- [x] rfcx/biodiversity-analytics#926
- [x] rfcx/engineering-support#174
- [x] rfcx/engineering-support#162 __ON STAGING NOW__
- [ ] Upload threshold for flagging is too low (4000)- Is this task for Stas?

## 4. User research @tiffanylee0125 
- [ ] Card Sorting Test for Navigation Header - recruit and launch
- [ ] Research Repository - metadata labels, platform selection 
- [ ] Shareback

## 5. Quality @antonyharfield @rassokhina-e @koonchaya 
- [x] Detect when playlist contains 500,000+, when creating PM job and show warning (Marconi) __ON STAGING NOW__
- [x] rfcx/biodiversity-analytics#928
- [x] rfcx/biodiversity-analytics#929
- [ ] Migrate legacy projects, permissions, sites to Core
- [ ] Migrate legacy audio files to Core
- [ ] Move Arbimon web frontend to Kubernetes, add Continuous Deployment
- [x] rfcx/arbimon#1098
- [x] rfcx/engineering-support#155 __ON STAGING NOW__

## 6. Web-Uploader performance @rassokhina-e 
- [x] rfcx/arbimon#1099 __ON STAGING NOW__
- [x] rfcx/arbimon#1100 __ON STAGING NOW__
- [ ] Test and launch

----

_Backup: Not included in the sprint goal, but still tracking..._

## Bio
- [ ] rfcx/biodiversity-analytics#880

## Species validation
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## Arbimon performance
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
