### ISSUE TITLE
Sprint Goal Q4-3 (10 - 23 Nov 2022)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#931]
# Goal: TODO

Capacity:
- @antonyharfield  3/10 (Mon 21 - Wed 23)

## 1. AED and Clustering @rassokhina-e 
- [x] rfcx/arbimon#1095 
- [x] rfcx/arbimon#1106

## 2. Soundscapes @antonyharfield
- [x] rfcx/arbimon-soundscapes#2
- [x] rfcx/engineering-support#183
- [x] rfcx/engineering-support#185
- [x] rfcx/arbimon#1107

## 3. User support @koonchaya  @rassokhina-e
- [x] rfcx/engineering-support#190
- [x] rfcx/engineering-support/issues/193

## 4. User research @tiffanylee0125 
- [ ] Card Sorting Test for Navigation Header - ?
- [ ] Research Repository - metadata labels, platform selection 

## 5. Quality @antonyharfield @rassokhina-e @koonchaya 
- [x] rfcx/biodiversity-analytics#932
- [x] rfcx/arbimon#1108
- [x] rfcx/biodiversity-analytics#929
- [ ] Move Arbimon web frontend to Kubernetes, add Continuous Deployment
- [ ] Migrate legacy audio files to Core
- [x] rfcx/arbimon#1098 ___CREATED PR___
- [x] Test Insights performance (activity page) on production
- [x] Move web uploader under Sites page in Arbimon
- [x] Show the user's first name, last name, and email when deleting the user from any project
- [ ] rfcx/biodiversity-analytics#933
- [x] rfcx/biodiversity-analytics#935
- [x] rfcx/arbimon#1116

----

_Backup: Not included in the sprint goal, but still tracking..._

## Species validation
- [x] rfcx/biodiversity-analytics#863
- [ ] User can see the model, input and job status
- [ ] Finalize the design for filters and sorting

## Arbimon performance
- [ ] Remove filter for species validation in Arbimon
- [ ] Add species validation number in the species page
