### ISSUE TITLE
Sprint Goal Q4-4 (23 Nov - 7 Dec)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#937]
# Primary Goal: Close out AED+Clustering OKR

## 1. AED and Clustering
- [x] rfcx/arbimon#1114
- [x] rfcx/engineering-support#205
- [x] Ensure science team has reviewed documentation
- [ ] Job limits
  - [x] rfcx/arbimon#1120
  - [x] Ensure job of 1000 recordings is meaningful (Marconi)
  - [x] rfcx/arbimon#1119

## 2. Soundscapes 
- [x] rfcx/arbimon-soundscapes#3
- [x] rfcx/arbimon-soundscapes#2

## 3. Species validation
- [ ] Review designs for validation with Antony
- [x] rfcx/biodiversity-analytics#863
  - [ ] rfcx/biodiversity-analytics#873 ____[PR](https://github.com/rfcx/biodiversity-analytics/pull/945)___
  - [ ] rfcx/biodiversity-analytics#874 ____[PR](https://github.com/rfcx/biodiversity-analytics/pull/945)___
  - [ ] rfcx/biodiversity-analytics#864 ___ON PROGRESS__
  - [x] rfcx/biodiversity-analytics#865
  - [x] rfcx/biodiversity-analytics#866

## 4. Quality
- [x] rfcx/arbimon#1116
- [x] Document style guide for HelpScout documents
- [x] #943
- [ ] Core-Arbimon integration
  - [x] rfcx/arbimon#1117
  - [x] rfcx/arbimon#1098 ___CREATED PR___

## 5. User support
- [x] Test and launch Uploader fixes
- [x] Clear backlog of soundscape/RFM jobs
- [x] rfcx/biodiversity-analytics#944
- [x] rfcx/engineering-support#198
- [x] [First dataset shows no data on Richness Insight reports#213](https://github.com/rfcx/engineering-support/issues/213)
- [x] [User cannot upload files with error "Server failed with processing your file"#211](https://github.com/rfcx/engineering-support/issues/211)
- [x] [Download species validation in PR project#209](https://github.com/rfcx/engineering-support/issues/209)

## 6. Future project preparation
- [x] New navigation structure - Verify proposed 1.0 on users (TreeJack test)
- [x] Educate “why free” and “how to contrib” - Specify requirements, design/write content 
- [x] Environmental data upload/visualize - Sketch proposed user flow

----

_Backup: Not included in the sprint goal, but still tracking..._
