### ISSUE TITLE
Sprint Goal Q4-5 (8 - 21 Dec)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#946]
# Primary Goal: Close out AED+Clustering OKR

## 1. AED and Clustering
- [x] rfcx/engineering-support#205
- [ ] Job limits
  - [ ] Ensure clustering cost is under $1000 per month
  - [x] rfcx/arbimon#1119

## 2. Soundscapes 
- [x] rfcx/arbimon-soundscapes#3
- [x] rfcx/arbimon-soundscapes#2

## 3. Species validation
- [x] rfcx/biodiversity-analytics#863
  - [x] rfcx/biodiversity-analytics#865
  - [x] rfcx/biodiversity-analytics#866

## 4. Quality
- [x] rfcx/arbimon#1117
- [x] rfcx/arbimon#1098

## 5. User support
- [x] rfcx/engineering-support#219
- [x] rfcx/engineering-support#215
- [x] rfcx/engineering-support#221
- [x] rfcx/arbimon#1127
- [x] rfcx/engineering-support#220
- [x] rfcx/engineering-support#222
- [x] rfcx/engineering-support#223
- [x] rfcx/engineering-support#224

## 6. Future project preparation
- [x] New navigation structure - Finalise structure
