### ISSUE TITLE
Sprint Goal Q4-6 (22 Dec - 4 Jan)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#951]
## 1. AED and Clustering
- [x] rfcx/engineering-support#205
- [ ] Ensure clustering cost is under $1000 per month

## 2. Soundscapes 
- [ ] rfcx/arbimon-soundscapes#5
- [ ] rfcx/arbimon-soundscapes#4
- [ ] Switch from sox to ffmpeg (more widely supported) for file conversion
- [ ] Run a performance comparison
- [ ] Update SDK docs on HelpScout

## 3. Species validation
- [ ] Connecting to existing APIs ______ PR created _____
- [ ] Propose changes to Core needed in 2023 to support validation

## 4. Quality
- [x] rfcx/arbimon#1098
- [ ] rfcx/biodiversity-analytics#950 ______ PR created _____

## 5. User support
- [x] rfcx/arbimon#1127
- [x] rfcx/engineering-support#232
- [x] rfcx/engineering-support#237
- [x] rfcx/arbimon#1132
- [ ] Complete/gather content for Arbimon newsletter
- [ ] Launch Uploader v1.5.3 Windows and Mac
- [x] rfcx/arbimon#1029
