### ISSUE TITLE
Sprint Goal Q1-1 (6 - 19 Jan)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#956]
## 1. Arbimon newsletter
- [x] rfcx/arbimon#1127
  - [x] Content prepared
  - [x] Content reviewed
  - [x] Sent

## 2. Windows Uploader
- [ ] Try building `drivelist` on Windows from source
- [ ] Explore options for removing `drivelist`
- [ ] Launch Uploader v1.5.3 Windows and Mac

## 3. Web Uploader
- [x] rfcx/arbimon#1132
- [ ] rfcx/arbimon#1135 (optional)

## 4. AED and Clustering
- [x] Ensure that the limit for AED job is 2,000 recordings
- [ ] Write test script and perform test (to check all functions work for normal user)
- [x] Invite 3 users to clustering (+ initial interview?)
- [ ] Follow-up interview with 3 users and compile feedback
- [ ] Ensure clustering cost is under $1000 per month
- [x] Enable AED+clustering for all projects
- [x] rfcx/engineering-support#205

## 6. User support
- [x] rfcx/engineering-support#238
- [x] rfcx/engineering-support#244
- [x] rfcx/engineering-support#245
- [x] rfcx/engineering-support#243
- [x] rfcx/engineering-support#237

## 7. OKR: New user experience
- [ ] Define arbimon.org content
- [ ] Plan how to implement new navigation
- [ ] R&D on how to do a SUS survey in Arbimon

## 8. OKR: Plan future improvements to Arbimon's visualizer workflows
- [ ] Engage Harvard UX team for semester project (+ kick-off by Jan)

---

_Not in the sprint goal, but still tracking..._

Species validation
- [ ] Connecting to existing APIs
- [ ] Propose changes to Core needed in 2023 to support validation

Soundscapes 
- [ ] rfcx/arbimon-soundscapes#5
- [ ] rfcx/arbimon-soundscapes#4
- [ ] Switch from sox to ffmpeg (more widely supported) for file conversion
- [ ] Run a performance comparison
- [ ] Update SDK docs on HelpScout
