### ISSUE TITLE
Sprint Goal Q1-2 (20 Jan-2 Feb)

### ISSUE THREAD

**Issue by rassokhina-e** [rfcx/arbimon#958]
## 1. Windows Uploader
- [x] Rollback to v1.4.x (without Song Meter support)
- [ ] Try building `drivelist` on Windows from source

## 2. Web Uploader
- [x] rfcx/arbimon#1141
- [x] Test new strategy on staging and production

## 3. AED and Clustering
- [x] rfcx/arbimon#1140
- [x] rfcx/arbimon#1142
- [x] rfcx/arbimon#1143
- [x] Share analysis of user research on AED+clustering

## 4. User support
- [x]  rfcx/engineering-support#255
- [x] rfcx/engineering-support#265
- [x] rfcx/engineering-support#263
- [x] rfcx/engineering-support#264
- [x] rfcx/engineering-support#266
- [x] rfcx/engineering-support#262 (optional)
- [ ] rfcx/engineering-support#246 (optional)
- [ ] rfcx/engineering-support#251 (optional)

## 5. Quality
- [ ] rfcx/arbimon#1144
- [ ] rfcx/arbimon#1139
- [x]  Check biodiversity incremental sync issue

## 6. OKR: New user experience
- [ ] Define arbimon.org content
- [ ] Plan how to implement new navigation
- [ ] R&D on how to do a SUS survey in Arbimon

## 7. OKR: Plan future improvements to Arbimon's visualizer workflows
- [ ] Kick off meeting with Harvard team

---

_Not in the sprint goal, but still tracking..._

### OKR: CNN workflow
- [ ] Propose changes to Core needed to support validation

### OKR: Soundscapes 
- [ ] `rfcx/arbimon-soundscapes#5`
- [ ] `rfcx/arbimon-soundscapes#4`
- [ ] Switch from sox to ffmpeg (more widely supported) for file conversion
- [ ] Run a performance comparison
- [ ] Update SDK docs on HelpScout
