### ISSUE TITLE
Sprint Goal Q1-3 (3 - 16 Feb)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#966]
## 1. Windows Uploader
- [x] Fix all issues after building v1.5.3 on the Windows 
- [x] Publish v1.5.3 for Mac and Windows

## 2. User support
- [x] rfcx/engineering-support#265
- [x] rfcx/engineering-support#266
- [x] rfcx/engineering-support#246
- [x] rfcx/engineering-support#251
- [ ] rfcx/biodiversity-analytics#971 (optional) - Made a pull request to add the markdown lib to support beautiful project description on the Arbimon side
- [x] rfcx/engineering-support#270
- [x] rfcx/engineering-support#279
- [x] rfcx/engineering-support#280

## 3. Quality
- [x] rfcx/biodiversity-analytics#967
- [x] In daily report on number of sites, recordings, and species, add number of PMs

## 4. OKR: New user experience
- [ ] Propose design for arbimon.org pages (based on existing styles)
- [ ] Gather content for website
- [ ] Start to implement new navigation
- [x] Sign up for Survate ($65/month) for usability survey in Arbimon OR explore alternate options

## 5. OKR: support decision making on ecosystem health:
- [ ] User interviews with conservation DM (WeForest, Galapagos)
- [ ] Interview analysis for internal + external scientists on Insight page.

## 6. OKR: Develop digital presence 
- [ ] ~Forum R&D: try out [www.discourse.org](https://www.discourse.org/pricing) to learn how we can style/integrate with arbimon.org~

---

_Not in the sprint goal, but still tracking..._

### Quality
- [ ] rfcx/arbimon#1149
- [ ] rfcx/arbimon#1144
- [ ] rfcx/arbimon#1139

### OKR: CNN workflow
- [ ] Propose changes to Core needed to support validation

### OKR: Soundscapes 
- [ ] `rfcx/arbimon-soundscapes#5`
- [ ] `rfcx/arbimon-soundscapes#4`
- [ ] Switch from sox to ffmpeg (more widely supported) for file conversion
- [ ] Run a performance comparison
- [ ] Update SDK docs on HelpScout
