### ISSUE TITLE
Sprint Goal Q1-4 (17 Feb - 02 March)

### ISSUE THREAD

**Issue by rassokhina-e** [rfcx/arbimon#973]
## 1. Quality
- [ ] Move the export recordings functionality to the background work
- [x] rfcx/core-arbimon-jobs#1 _____IN PROGRESS_____
- [x] #977

## 2. User support
- [x] [Uploader windows version showed black screen](https://github.com/rfcx/engineering-support/issues/305)
- [ ] [Species detected in Richness should not mark all species in all datasets](https://github.com/rfcx/biodiversity-analytics/issues/979)
- [x] [Remove download button from Arbimon Insight for public user](https://github.com/rfcx/biodiversity-analytics/issues/970)
- [ ] [Fix sum of the percentage of Species highlight and Threatened species on Arbimon insight dashboard#285](https://github.com/rfcx/biodiversity-analytics/issues/978)
- [x] [Python SDK upload method might not be working](https://github.com/rfcx/arbimon-sdk-python/issues/5)
- [x] [Open all of those navigation links in a new tab](https://github.com/rfcx/arbimon/issues/1154)
- [x] [Dashboard option in Arbimon should not redirect to Guardian dashboard](https://github.com/rfcx/arbimon/issues/1155) 
- [ ] [Add ability to pause or stop uploading a specific site on Uploader app](https://github.com/rfcx/arbimon-uploader/issues/181) (optional)

## 3. OKR: Biz Dev bring in new Arbimon projects from existing users
- [x] Finalise design of “Create project” page
- [ ] Implement “Create project” page

## 4. OKR: New user experience
- [ ] Prepare content (landing, featured stories, news, how it works) for website
- [ ] Design non-standard components (impact, how it works)
- [x] rfcx/biodiversity-analytics#974

## 5. OKR: support decision-making on ecosystem health
- [ ] Interview analysis for internal + external scientists on the Insight page.

## 6. OKR: CNN workflow
- [ ] Incorporate existing batch CNN pages into new navigation

---

_Not in the sprint goal, but still tracking..._

### Soundscapes 
- [ ] `rfcx/arbimon-soundscapes#5`
- [ ] `rfcx/arbimon-soundscapes#4`
- [ ] Switch from sox to ffmpeg (more widely supported) for file conversion
- [ ] Run a performance comparison
- [ ] Update SDK docs on HelpScout
