### ISSUE TITLE
Sprint Goal Q1-5 (3 - 16 Mar)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#980]
## 1. Quality
- [x] rfcx/core-arbimon-jobs#1 ____IN PROGRESS____
- [x] rfcx/arbimon#1173
- [ ] Download buttons
  - [x] rfcx/arbimon#1172
  - [x] rfcx/arbimon#1164
  - [x] rfcx/arbimon#1176
  - [ ] (Optional) If it is a heavy query then use background job and send email
  - [ ] (Optional) If the email attachment is large then don't attach it
- [x] rfcx/arbimon#1112 ____IN CODE REVIEW_____
- [x] rfcx/arbimon-sdk-python#6

## 2. User support
- [x] rfcx/arbimon#1170
- [x] rfcx/arbimon#1179 
- [x] rfcx/arbimon#1180
- [x] rfcx/biodiversity-analytics#981
- [x] rfcx/biodiversity-analytics#979
- [x] rfcx/arbimon#1174

## 3. OKR: Biz Dev bring in new Arbimon projects from existing users
- [x] rfcx/biodiversity-analytics#982

## 4. OKR: New user experience
- [x] rfcx/biodiversity-analytics#974
- [x] rfcx/biodiversity-analytics#984
- [x] rfcx/biodiversity-analytics#985
  - [x] Hero
  - [x] Map/impact
  - [x] What we do
  - [x] Features
  - [x] How it works
  - [x] Testimonials
  - [x] Partners
- [x] rfcx/biodiversity-analytics#986
  - [x] List page
  - [ ] Detail page
- [x] rfcx/biodiversity-analytics#987
  - [x] Steps
  - [x] CTA
  - [x] Analyes
- [x] rfcx/biodiversity-analytics#988
- [x] rfcx/biodiversity-analytics#989
- [x] rfcx/biodiversity-analytics#990
- [x] rfcx/biodiversity-analytics#991

## 5. OKR: support decision-making on ecosystem health
- [ ] Interview analysis for internal + external scientists on the Insight page.

## 6. Upload files for TNC Myanmar
- [x] rfcx/engineering-support#325
