### ISSUE TITLE
Sprint Goal Q1-6 (17 - 30 Mar)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/arbimon#996]
## 1. Quality
- [ ] Migrating recordings to Core
  - [x] rfcx/core-arbimon-jobs#1 
  - [x] rfcx/core-arbimon-jobs#5
  - [x] rfcx/core-arbimon-jobs#6
  - [ ] Complete another 10 projects (choose most frequently used)
  - [x] Delete any legacy test projects from Arbimon db
- [ ] Download buttons
  - [x] rfcx/arbimon#1190
  - [x] If it is a heavy query then use background job and send email
  - [ ] If the email attachment is large then don't attach it
- [x] rfcx/arbimon#1192 
- [x] rfcx/biodiversity-analytics#995

## 2. User support
Arbimon
- [x] rfcx/arbimon#1174 
- [x] rfcx/arbimon#1184
- [x] rfcx/arbimon#1183 
- [x] rfcx/arbimon#1191 
- [x] rfcx/arbimon#1189

Uploader
- [x] rfcx/arbimon-uploader#185
- [ ] (optional) rfcx/arbimon-uploader#186

## 3. OKR: CNN journey
- [x] Plan out, gain consensus and communicate a roadmap of features for Arbimon @antonyharfield 
- [x] rfcx/biodiversity-analytics#998

## 4. OKR: New user experience
- [x] rfcx/biodiversity-analytics#986
- [x] rfcx/biodiversity-analytics#990
- [x] rfcx/biodiversity-analytics#991
- [x] rfcx/biodiversity-analytics#999
- [x] rfcx/biodiversity-analytics#1000
- [x] rfcx/biodiversity-analytics#1001
- [x] rfcx/biodiversity-analytics#1002

## 5. OKR: Biz Dev bring in new Arbimon projects from existing users
- [x] Review the design to make sure we are meeting Chrissy's requirements @antonyharfield

## 6. Upload files for TNC Myanmar
- [x] rfcx/engineering-support#325
